// Command udb is a version-matched launcher for the UDB control-plane CLI,
// bundled with the Go SDK.
//
// Generated by `udb sdk generate` from the embedded proto descriptor set. Edit the template under sdk-templates/<lang>/, not this file.
//
// Installing the SDK and running `go install github.com/fahara02/udb/sdk/go/cmd/udb@v0.3.1`
// puts a `udb` binary on your $GOBIN. That binary does NOT reimplement the CLI;
// it locates the real, version-matched `udb` release binary and execs it,
// forwarding all arguments, stdin/stdout/stderr, and the exit code:
//
//  1. If $UDB_BIN points at an executable, use it.
//  2. Else if a `udb` of the matching version (v0.3.1) is already on
//     $PATH (and is not this launcher), exec that.
//  3. Else download the matching release asset from
//     github.com/fahara02/udb (tag v0.3.1) for the current GOOS/GOARCH
//     into a per-user cache dir, then exec it. Subsequent runs reuse the cache.
//
// This keeps the CLI and SDK versions locked together: `go install ...@vX`
// always launches udb vX.
package main

import (
	"archive/tar"
	"archive/zip"
	"bytes"
	"compress/gzip"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"time"
)

// udbVersion is baked at SDK generation time and pins the CLI release this
// launcher resolves.
const udbVersion = "0.3.1"

const (
	githubOwner = "fahara02"
	githubRepo  = "udb"
)

func main() {
	bin, err := resolveBinary()
	if err != nil {
		fmt.Fprintf(os.Stderr, "udb-launcher: %v\n", err)
		os.Exit(1)
	}
	code, err := run(bin, os.Args[1:])
	if err != nil {
		fmt.Fprintf(os.Stderr, "udb-launcher: %v\n", err)
		os.Exit(1)
	}
	os.Exit(code)
}

// run execs the resolved binary, forwarding stdio, and returns its exit code.
func run(bin string, args []string) (int, error) {
	cmd := exec.Command(bin, args...)
	cmd.Stdin = os.Stdin
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Env = os.Environ()
	if err := cmd.Run(); err != nil {
		var exitErr *exec.ExitError
		if errors.As(err, &exitErr) {
			return exitErr.ExitCode(), nil
		}
		return 1, err
	}
	return 0, nil
}

// resolveBinary finds (or downloads) the version-matched udb binary.
func resolveBinary() (string, error) {
	// 1. Explicit override.
	if env := os.Getenv("UDB_BIN"); env != "" {
		if isExecutable(env) {
			return env, nil
		}
		return "", fmt.Errorf("UDB_BIN=%q is not an executable file", env)
	}

	// 2. Cached download from a previous run.
	cached := cachedBinaryPath()
	if isExecutable(cached) {
		return cached, nil
	}

	// 3. A matching-version udb already on PATH (skip ourselves).
	if p := lookPathMatching(); p != "" {
		return p, nil
	}

	// 4. Download the matching release asset.
	if os.Getenv("UDB_NO_DOWNLOAD") != "" {
		return "", fmt.Errorf(
			"no udb v%s found (UDB_BIN unset, not on PATH, UDB_NO_DOWNLOAD set)", udbVersion)
	}
	if err := downloadRelease(cached); err != nil {
		return "", fmt.Errorf("downloading udb v%s: %w", udbVersion, err)
	}
	return cached, nil
}

func isExecutable(path string) bool {
	fi, err := os.Stat(path)
	if err != nil || fi.IsDir() {
		return false
	}
	if runtime.GOOS == "windows" {
		return true
	}
	return fi.Mode().Perm()&0o111 != 0
}

// lookPathMatching returns a `udb` on PATH whose `--version` reports udbVersion,
// excluding this launcher binary itself.
func lookPathMatching() string {
	self, _ := os.Executable()
	self, _ = filepath.Abs(self)
	candidate, err := exec.LookPath(exeName("udb"))
	if err != nil {
		return ""
	}
	if abs, _ := filepath.Abs(candidate); abs == self {
		return ""
	}
	out, err := exec.Command(candidate, "--version").Output()
	if err != nil {
		return ""
	}
	if strings.Contains(string(out), udbVersion) {
		return candidate
	}
	return ""
}

func exeName(base string) string {
	if runtime.GOOS == "windows" {
		return base + ".exe"
	}
	return base
}

// cacheDir is the per-user directory caching downloaded udb binaries.
func cacheDir() string {
	base, err := os.UserCacheDir()
	if err != nil || base == "" {
		base = os.TempDir()
	}
	return filepath.Join(base, "udb", "bin", "v"+udbVersion)
}

func cachedBinaryPath() string {
	return filepath.Join(cacheDir(), exeName("udb"))
}

// assetName builds the per-OS/arch release asset filename. It mirrors the UDB
// release convention: udb-<version>-<os>-<arch>.<ext>.
//
//	linux/darwin -> .tar.gz, windows -> .zip
func assetName() (name, ext string) {
	goos := runtime.GOOS
	goarch := runtime.GOARCH
	if goos == "windows" {
		ext = "zip"
	} else {
		ext = "tar.gz"
	}
	name = fmt.Sprintf("udb-v%s-%s-%s.%s", udbVersion, goos, goarch, ext)
	return name, ext
}

func releaseURL() string {
	name, _ := assetName()
	return fmt.Sprintf(
		"https://github.com/%s/%s/releases/download/v%s/%s",
		githubOwner, githubRepo, udbVersion, name)
}

// downloadRelease fetches and extracts the udb binary into dest.
func downloadRelease(dest string) error {
	if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
		return err
	}
	url := releaseURL()
	fmt.Fprintf(os.Stderr, "udb-launcher: fetching %s\n", url)

	client := &http.Client{Timeout: 5 * time.Minute}
	resp, err := client.Get(url)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("unexpected status %s fetching %s", resp.Status, url)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return err
	}

	_, ext := assetName()
	tmp := dest + ".tmp"
	if err := extractBinary(body, ext, tmp); err != nil {
		return err
	}
	if runtime.GOOS != "windows" {
		_ = os.Chmod(tmp, 0o755)
	}
	return os.Rename(tmp, dest)
}

// extractBinary pulls the udb executable out of an archive and writes it to out.
func extractBinary(archive []byte, ext, out string) error {
	switch ext {
	case "zip":
		return extractZip(archive, out)
	case "tar.gz":
		return extractTarGz(archive, out)
	default:
		return fmt.Errorf("unsupported archive extension %q", ext)
	}
}

func extractZip(archive []byte, out string) error {
	zr, err := zip.NewReader(bytes.NewReader(archive), int64(len(archive)))
	if err != nil {
		return err
	}
	want := exeName("udb")
	for _, f := range zr.File {
		if filepath.Base(f.Name) != want {
			continue
		}
		rc, err := f.Open()
		if err != nil {
			return err
		}
		defer rc.Close()
		return writeFile(out, rc)
	}
	return fmt.Errorf("%q not found in zip archive", want)
}

func extractTarGz(archive []byte, out string) error {
	gz, err := gzip.NewReader(bytes.NewReader(archive))
	if err != nil {
		return err
	}
	defer gz.Close()
	tr := tar.NewReader(gz)
	want := exeName("udb")
	for {
		hdr, err := tr.Next()
		if errors.Is(err, io.EOF) {
			break
		}
		if err != nil {
			return err
		}
		if filepath.Base(hdr.Name) != want {
			continue
		}
		return writeFile(out, tr)
	}
	return fmt.Errorf("%q not found in tar.gz archive", want)
}

func writeFile(path string, r io.Reader) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	_, err = io.Copy(f, r)
	return err
}
