// Command udb is a version-matched launcher for the UDB control-plane CLI,
// bundled with the Go SDK.
//
// Generated by `udb sdk generate` from the embedded proto descriptor set. Edit the template under sdk-templates/<lang>/, not this file.
//
// Installing the SDK and running `go install github.com/fahara02/udb/sdk/go/cmd/udb@v0.4.15`
// puts a `udb` binary on your $GOBIN. That binary does NOT reimplement the CLI;
// it locates the real, version-matched `udb` release binary and execs it,
// forwarding all arguments, stdin/stdout/stderr, and the exit code:
//
//  1. If $UDB_BIN points at an executable, use it.
//  2. Else if a `udb` of the matching version (v0.4.15) is already on
//     $PATH (and is not this launcher), exec that.
//  3. Else download the matching release asset from
//     github.com/fahara02/udb (tag v0.4.15) for the current GOOS/GOARCH
//     into a per-user cache dir, then exec it. Subsequent runs reuse the cache.
//
// The release assets are RAW executables named udb-<os>-<arch>[-<variant>][.exe]
// (e.g. udb-linux-amd64, udb-windows-amd64.exe, udb-darwin-arm64). Set
// UDB_BIN_VARIANT to pick a non-default build (e.g. "full" -> udb-linux-amd64-full);
// "portable" or empty selects the default unsuffixed asset.
//
// This keeps the CLI and SDK versions locked together: `go install ...@vX`
// always launches udb vX.
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"time"
)

// udbVersion is baked at SDK generation time and pins the CLI release this
// launcher resolves.
const udbVersion = "0.4.15"

const (
	githubOwner = "fahara02"
	githubRepo  = "udb"
)

func main() {
	bin, err := resolveBinary()
	if err != nil {
		fmt.Fprintf(os.Stderr, "udb-launcher: %v\n", err)
		os.Exit(1)
	}
	code, err := run(bin, os.Args[1:])
	if err != nil {
		fmt.Fprintf(os.Stderr, "udb-launcher: %v\n", err)
		os.Exit(1)
	}
	os.Exit(code)
}

// run execs the resolved binary, forwarding stdio, and returns its exit code.
func run(bin string, args []string) (int, error) {
	cmd := exec.Command(bin, args...)
	cmd.Stdin = os.Stdin
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Env = os.Environ()
	if err := cmd.Run(); err != nil {
		var exitErr *exec.ExitError
		if errors.As(err, &exitErr) {
			return exitErr.ExitCode(), nil
		}
		return 1, err
	}
	return 0, nil
}

// resolveBinary finds (or downloads) the version-matched udb binary.
func resolveBinary() (string, error) {
	// 1. Explicit override.
	if env := os.Getenv("UDB_BIN"); env != "" {
		if isExecutable(env) {
			return env, nil
		}
		return "", fmt.Errorf("UDB_BIN=%q is not an executable file", env)
	}

	// 2. Cached download from a previous run.
	cached := cachedBinaryPath()
	if isExecutable(cached) {
		return cached, nil
	}

	// 3. A matching-version udb already on PATH (skip ourselves).
	if p := lookPathMatching(); p != "" {
		return p, nil
	}

	// 4. Download the matching release asset.
	if os.Getenv("UDB_NO_DOWNLOAD") != "" {
		return "", fmt.Errorf(
			"no udb v%s found (UDB_BIN unset, not on PATH, UDB_NO_DOWNLOAD set)", udbVersion)
	}
	if err := downloadRelease(cached); err != nil {
		return "", fmt.Errorf("downloading udb v%s: %w", udbVersion, err)
	}
	return cached, nil
}

func isExecutable(path string) bool {
	fi, err := os.Stat(path)
	if err != nil || fi.IsDir() {
		return false
	}
	if runtime.GOOS == "windows" {
		return true
	}
	return fi.Mode().Perm()&0o111 != 0
}

// lookPathMatching returns a `udb` on PATH whose `--version` reports udbVersion,
// excluding this launcher binary itself.
func lookPathMatching() string {
	self, _ := os.Executable()
	self, _ = filepath.Abs(self)
	candidate, err := exec.LookPath(exeName("udb"))
	if err != nil {
		return ""
	}
	if abs, _ := filepath.Abs(candidate); abs == self {
		return ""
	}
	out, err := exec.Command(candidate, "--version").Output()
	if err != nil {
		return ""
	}
	if strings.Contains(string(out), udbVersion) {
		return candidate
	}
	return ""
}

func exeName(base string) string {
	if runtime.GOOS == "windows" {
		return base + ".exe"
	}
	return base
}

// cacheDir is the per-user directory caching downloaded udb binaries.
func cacheDir() string {
	base, err := os.UserCacheDir()
	if err != nil || base == "" {
		base = os.TempDir()
	}
	return filepath.Join(base, "udb", "bin", "v"+udbVersion)
}

func cachedBinaryPath() string {
	return filepath.Join(cacheDir(), exeName("udb"))
}

// assetName builds the per-OS/arch release asset filename, matching the published
// release scheme: udb-<os>-<arch>[-<variant>][.exe], a RAW executable with NO
// version in the name and NO archive extension.
//
//   - <os>:   runtime.GOOS verbatim (linux | darwin | windows).
//   - <arch>: runtime.GOARCH (amd64 | arm64 preferred; others pass through).
//   - <variant>: UDB_BIN_VARIANT; unset/empty/"portable" omits the suffix,
//     any other value is appended as "-<value>" (e.g. "full" -> "-full").
//   - <ext>:  ".exe" on Windows, otherwise empty.
//
// Examples: udb-linux-amd64, udb-windows-amd64.exe, udb-darwin-arm64,
// udb-linux-amd64-full.
func assetName() string {
	goos := runtime.GOOS
	goarch := runtime.GOARCH

	variant := ""
	if v := strings.TrimSpace(os.Getenv("UDB_BIN_VARIANT")); v != "" && v != "portable" {
		variant = "-" + v
	}

	ext := ""
	if goos == "windows" {
		ext = ".exe"
	}

	return fmt.Sprintf("udb-%s-%s%s%s", goos, goarch, variant, ext)
}

func releaseURL() string {
	return fmt.Sprintf(
		"https://github.com/%s/%s/releases/download/v%s/%s",
		githubOwner, githubRepo, udbVersion, assetName())
}

// downloadRelease fetches the raw udb executable and installs it at dest. The
// asset is a plain binary (no archive), so the bytes are written directly to a
// temp file, made executable on non-Windows, then atomically renamed into place.
// A best-effort sha256 check against the `<asset>.sha256` sidecar guards against
// truncated/corrupted downloads; a missing sidecar is not fatal.
func downloadRelease(dest string) error {
	if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
		return err
	}
	url := releaseURL()
	fmt.Fprintf(os.Stderr, "udb-launcher: fetching %s\n", url)

	client := &http.Client{Timeout: 5 * time.Minute}
	body, err := fetch(client, url)
	if err != nil {
		return err
	}

	if err := verifyChecksum(client, url, body); err != nil {
		return err
	}

	tmp := dest + ".tmp"
	if err := os.WriteFile(tmp, body, 0o755); err != nil {
		return err
	}
	if runtime.GOOS != "windows" {
		_ = os.Chmod(tmp, 0o755)
	}
	return os.Rename(tmp, dest)
}

// fetch GETs url and returns its body, erroring on any non-200 status.
func fetch(client *http.Client, url string) ([]byte, error) {
	resp, err := client.Get(url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("unexpected status %s fetching %s", resp.Status, url)
	}
	return io.ReadAll(resp.Body)
}

// verifyChecksum does a best-effort sha256 verification of body against the
// `<url>.sha256` sidecar. A 404 (no sidecar published) is treated as success;
// a present-but-mismatched checksum is a hard error.
func verifyChecksum(client *http.Client, url string, body []byte) error {
	resp, err := client.Get(url + ".sha256")
	if err != nil {
		// Network hiccup on the sidecar alone shouldn't block a good download.
		return nil
	}
	defer resp.Body.Close()
	if resp.StatusCode == http.StatusNotFound {
		return nil
	}
	if resp.StatusCode != http.StatusOK {
		return nil
	}
	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil
	}
	want := parseSha256(string(raw))
	if want == "" {
		return nil
	}
	got := sha256.Sum256(body)
	if !strings.EqualFold(want, hex.EncodeToString(got[:])) {
		return fmt.Errorf("checksum mismatch for %s: got %s, want %s",
			url, hex.EncodeToString(got[:]), want)
	}
	return nil
}

// parseSha256 extracts the hex digest from a sha256sum-style sidecar line
// ("<hex>  <filename>"); it also tolerates a bare digest.
func parseSha256(s string) string {
	for _, line := range strings.Split(s, "\n") {
		fields := strings.Fields(line)
		if len(fields) == 0 {
			continue
		}
		return fields[0]
	}
	return ""
}
