package udbclient

// Generated by `udb sdk generate` from the embedded proto descriptor set. Edit the template under sdk-templates/<lang>/, not this file.
//
// generated_client.go is a GENERATED robustness / forwarding layer that COMPOSES
// WITH the hand-written udbclient package (client.go, auth*.go, negotiation.go).
// It NEVER replaces them. It adds, on top of the existing buf-generated gRPC
// stubs:
//
//   - configurable per-call deadline / timeout
//   - retry with exponential backoff + jitter on transient gRPC codes
//     (UNAVAILABLE, RESOURCE_EXHAUSTED; plus DEADLINE_EXCEEDED only for
//     read-only RPCs), never retrying non-idempotent streaming RPCs
//   - TLS / credential wiring (via the dial options you pass)
//   - metadata injection (the same 8 UDB headers as Client.Context, plus
//     authorization / api-key / request-id)
//   - typed error mapping (unpacks the `udb-error-detail-bin` trailer into a
//     typed *Error, else a clean error)
//
// It deliberately speaks the gRPC wire generically through
// grpc.ClientConnInterface.Invoke / NewStream keyed on each RPC's full method
// path, so it needs NO per-message Go type imports and stays valid as the proto
// surface grows. To make a fully typed call, keep using the hand-written
// udbclient.Client / udbclient.AuthClient wrappers — this layer governs the
// connection (interceptors) those wrappers run on, plus low-level escape
// hatches for RPCs that don't yet have a typed helper.
//
// Covers 262 RPCs across 16 services
// (UDB v0.3.5, wire protocol 1.0.0).

import (
	"context"
	"errors"
	"fmt"
	"math"
	"math/rand"
	"time"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/keepalive"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
)

// Keepalive defaults for the long-lived UDB channel. They keep an otherwise idle
// HTTP/2 connection warm so it does not drop to IDLE (gRPC default ~300s) and pay
// a fresh TCP+TLS+HTTP/2 handshake on the next RPC. Construct the channel ONCE and
// reuse it across all calls (see DialOptions); these are then a pure win.
const (
	keepaliveTime    = 30 * time.Second // ping an idle connection this often
	keepaliveTimeout = 10 * time.Second // wait this long for the ping ack before closing
)

// SDKVersion is the UDB release this generated layer was rendered from. It is
// baked at generation time and is the version the bundled `udb` CLI launcher
// (cmd/udb) will resolve.
const SDKVersion = "0.3.5"

// GeneratedProtocolVersion mirrors the wire protocol this layer targets. It is
// the generated companion to the hand-written udbclient.ProtocolVersion and is
// kept identical; both are asserted equal at package init below.
const GeneratedProtocolVersion = "1.0.0"

// errorDetailTrailer is the binary gRPC trailer the broker sets to a serialized
// udb.entity.v1.ErrorDetail. We surface it on *Error without depending on the
// generated message type (callers that want the decoded proto can unmarshal
// Error.DetailBin themselves).
const errorDetailTrailer = "udb-error-detail-bin"

// RetryConfig controls the backoff retry behavior of the generated wrappers.
// The zero value is unusable; use DefaultRetryConfig().
type RetryConfig struct {
	MaxAttempts  int           // total tries including the first; <=1 disables retry
	BaseBackoff  time.Duration // backoff for the first retry
	MaxBackoff   time.Duration // backoff ceiling
	Jitter       float64       // 0..1 fraction of randomized jitter added to each backoff
	RetryOnCodes []codes.Code  // transient codes retried only for read-only unary RPCs
}

// DefaultRetryConfig returns the proven UDB defaults: 4 attempts, 100ms base,
// 5s ceiling, full jitter, retrying only read-only unary RPCs on transient codes.
// Mutating RPCs are never retried automatically.
func DefaultRetryConfig() RetryConfig {
	return RetryConfig{
		MaxAttempts: 4,
		BaseBackoff: 100 * time.Millisecond,
		MaxBackoff:  5 * time.Second,
		Jitter:      1.0,
		RetryOnCodes: []codes.Code{
			codes.Unavailable,
			codes.ResourceExhausted,
		},
	}
}

func (rc RetryConfig) retryable(code codes.Code) bool {
	for _, c := range rc.RetryOnCodes {
		if c == code {
			return true
		}
	}
	return false
}

func (rc RetryConfig) retryableForRPC(code codes.Code, readOnly bool) bool {
	if !readOnly {
		return false
	}
	if code == codes.DeadlineExceeded {
		return true
	}
	return rc.retryable(code)
}

func (rc RetryConfig) backoff(attempt int) time.Duration {
	// attempt is 0-based for the first *retry*.
	d := float64(rc.BaseBackoff) * math.Pow(2, float64(attempt))
	if d > float64(rc.MaxBackoff) {
		d = float64(rc.MaxBackoff)
	}
	if rc.Jitter > 0 {
		j := d * rc.Jitter * rand.Float64()
		d = d - (d * rc.Jitter) + j
		if d < 0 {
			d = 0
		}
	}
	return time.Duration(d)
}

// Error is the typed error the generated layer maps gRPC failures to. It always
// carries the gRPC code/message; when the broker attached a serialized
// ErrorDetail trailer, DetailBin holds its raw bytes for the caller to decode.
type Error struct {
	Code      codes.Code
	Message   string
	RPC       string // full method path, e.g. /udb.services.v1.DataBroker/Select
	DetailBin []byte // raw udb.entity.v1.ErrorDetail bytes, or nil
	cause     error
}

func (e *Error) Error() string {
	if len(e.DetailBin) > 0 {
		return fmt.Sprintf("udb %s: %s (%s) [+error-detail %dB]", e.RPC, e.Message, e.Code, len(e.DetailBin))
	}
	return fmt.Sprintf("udb %s: %s (%s)", e.RPC, e.Message, e.Code)
}

func (e *Error) Unwrap() error { return e.cause }

// mapError converts a gRPC error (with optional trailer metadata) into *Error.
// A nil err returns nil.
func mapError(rpcPath string, err error, trailer metadata.MD) error {
	if err == nil {
		return nil
	}
	st, _ := status.FromError(err)
	out := &Error{
		Code:    st.Code(),
		Message: st.Message(),
		RPC:     rpcPath,
		cause:   err,
	}
	if vals := trailer.Get(errorDetailTrailer); len(vals) > 0 {
		out.DetailBin = []byte(vals[len(vals)-1])
	}
	return out
}

// Options configures a GeneratedClient.
type Options struct {
	// Meta is attached as the 8 UDB headers on every outgoing call, exactly as
	// the hand-written Client.Context does.
	Meta Metadata
	// CallTimeout, when > 0, is applied as a per-call deadline if the caller's
	// context has none.
	CallTimeout time.Duration
	// Retry governs backoff retries. Defaults to DefaultRetryConfig() when zero.
	Retry RetryConfig
	// Authorization, when non-empty, is sent as the `authorization` header
	// (e.g. "Bearer <jwt>").
	Authorization string
	// APIKey, when non-empty, is sent as the `x-api-key` header.
	APIKey string
	// RequestID, when non-empty, is sent as the `x-request-id` header. When
	// empty a per-call id is derived from Meta.CorrelationID if set.
	RequestID string
}

func (o Options) withDefaults() Options {
	if o.Retry.MaxAttempts == 0 {
		o.Retry = DefaultRetryConfig()
	}
	return o
}

// GeneratedClient is the robustness layer. It holds a gRPC connection and the
// options applied to every wrapped call. Build it from an existing
// *grpc.ClientConn (so TLS / credentials / dial options are entirely yours),
// then either:
//
//   - use the hand-written typed wrappers (udbclient.New(gc.Conn(), meta), …)
//     which inherit nothing extra, OR
//   - dial through DialOptions() so the retry/metadata/error interceptors apply
//     to those typed wrappers automatically, OR
//   - call gc.InvokeUnary / gc.NewServerStream / gc.NewClientStream for RPCs
//     without a typed helper.
type GeneratedClient struct {
	conn grpc.ClientConnInterface
	opt  Options
}

// NewGenerated wraps an existing connection. The connection's transport
// security (TLS/insecure) and credentials are whatever you configured when you
// dialed it; this layer never downgrades them.
func NewGenerated(conn grpc.ClientConnInterface, opt Options) *GeneratedClient {
	return &GeneratedClient{conn: conn, opt: opt.withDefaults()}
}

// Conn exposes the underlying connection so the hand-written typed wrappers can
// be built on the same channel: udbclient.New(gc.Conn(), gc.Meta()).
func (g *GeneratedClient) Conn() grpc.ClientConnInterface { return g.conn }

// Meta returns the configured caller Metadata.
func (g *GeneratedClient) Meta() Metadata { return g.opt.Meta }

// outgoingContext attaches the 8 UDB headers plus optional auth / api-key /
// request-id, reusing joinScopes from the hand-written client.go.
func (g *GeneratedClient) outgoingContext(ctx context.Context) context.Context {
	m := g.opt.Meta
	pairs := []string{
		"x-tenant-id", m.TenantID,
		"x-user-id", m.UserID,
		"x-purpose", m.Purpose,
		"x-correlation-id", m.CorrelationID,
		"x-service-identity", m.ServiceIdentity,
		"x-udb-project-id", m.ProjectID,
		"x-udb-client-catalog-version", m.ClientCatalogVersion,
	}
	if len(m.Scopes) > 0 {
		pairs = append(pairs, "x-scopes", joinScopes(m.Scopes))
	}
	if g.opt.Authorization != "" {
		pairs = append(pairs, "authorization", g.opt.Authorization)
	}
	if g.opt.APIKey != "" {
		pairs = append(pairs, "x-api-key", g.opt.APIKey)
	}
	if rid := g.opt.RequestID; rid != "" {
		pairs = append(pairs, "x-request-id", rid)
	} else if m.CorrelationID != "" {
		pairs = append(pairs, "x-request-id", m.CorrelationID)
	}
	return metadata.AppendToOutgoingContext(ctx, pairs...)
}

func (g *GeneratedClient) withDeadline(ctx context.Context) (context.Context, context.CancelFunc) {
	if g.opt.CallTimeout <= 0 {
		return ctx, func() {}
	}
	if _, ok := ctx.Deadline(); ok {
		return ctx, func() {}
	}
	return context.WithTimeout(ctx, g.opt.CallTimeout)
}

// InvokeUnary performs a unary RPC by full method path with metadata injection,
// per-call deadline, retry with backoff, and typed error mapping. req/reply are
// proto.Message values (the generated request/response types from ./gen). This
// is the engine the typed wrappers below delegate to.
func (g *GeneratedClient) InvokeUnary(ctx context.Context, fullMethod string, req, reply any, opts ...grpc.CallOption) error {
	rc := g.opt.Retry
	readOnly := isReadOnlyUnaryRPC(fullMethod)
	var lastErr error
	for attempt := 0; attempt < max(1, rc.MaxAttempts); attempt++ {
		if attempt > 0 {
			select {
			case <-time.After(rc.backoff(attempt - 1)):
			case <-ctx.Done():
				return mapError(fullMethod, ctx.Err(), nil)
			}
		}
		callCtx, cancel := g.withDeadline(g.outgoingContext(ctx))
		var trailer metadata.MD
		callOpts := append([]grpc.CallOption{grpc.Trailer(&trailer)}, opts...)
		err := g.conn.Invoke(callCtx, fullMethod, req, reply, callOpts...)
		cancel()
		if err == nil {
			return nil
		}
		lastErr = mapError(fullMethod, err, trailer)
		if !rc.retryableForRPC(status.Code(err), readOnly) {
			return lastErr
		}
	}
	return lastErr
}

// NewServerStream opens a server-streaming RPC. Streaming RPCs are NOT retried
// here (the stream may have already produced data); retry is the caller's
// decision. Metadata and per-call deadline still apply.
func (g *GeneratedClient) NewServerStream(ctx context.Context, fullMethod string, desc *grpc.StreamDesc, req any, opts ...grpc.CallOption) (grpc.ClientStream, error) {
	callCtx, cancel := g.withDeadline(g.outgoingContext(ctx))
	cs, err := g.conn.NewStream(callCtx, desc, fullMethod, opts...)
	if err != nil {
		cancel()
		return nil, mapError(fullMethod, err, nil)
	}
	if req != nil {
		if err := cs.SendMsg(req); err != nil {
			cancel()
			return nil, mapError(fullMethod, err, nil)
		}
		if err := cs.CloseSend(); err != nil {
			cancel()
			return nil, mapError(fullMethod, err, nil)
		}
	}
	return &cancelOnRecvStream{ClientStream: cs, cancel: cancel}, nil
}

// NewClientStream opens a client-streaming or bidi RPC. Never retried (the body
// is non-idempotent). Metadata and per-call deadline still apply.
func (g *GeneratedClient) NewClientStream(ctx context.Context, fullMethod string, desc *grpc.StreamDesc, opts ...grpc.CallOption) (grpc.ClientStream, error) {
	callCtx, cancel := g.withDeadline(g.outgoingContext(ctx))
	cs, err := g.conn.NewStream(callCtx, desc, fullMethod, opts...)
	if err != nil {
		cancel()
		return nil, mapError(fullMethod, err, nil)
	}
	return &cancelOnCloseStream{ClientStream: cs, cancel: cancel}, nil
}

type cancelOnRecvStream struct {
	grpc.ClientStream
	cancel context.CancelFunc
}

func (s *cancelOnRecvStream) RecvMsg(m any) error {
	err := s.ClientStream.RecvMsg(m)
	if err != nil {
		s.cancel()
	}
	return err
}

type cancelOnCloseStream struct {
	grpc.ClientStream
	cancel context.CancelFunc
}

func (s *cancelOnCloseStream) RecvMsg(m any) error {
	err := s.ClientStream.RecvMsg(m)
	if err != nil {
		s.cancel()
	}
	return err
}

func (s *cancelOnCloseStream) CloseSend() error {
	err := s.ClientStream.CloseSend()
	s.cancel()
	return err
}

// ── Dial-option interceptors ─────────────────────────────────────────────────
//
// Prefer these when you want the typed hand-written wrappers (Client, AuthClient)
// to gain retry/metadata/error-mapping transparently. Pass them to
// grpc.NewClient(target, append(yourSecurityOpts, gc.DialOptions()...)...).

// DialOptions returns the unary + stream interceptors that apply this client's
// metadata, deadline, retry for read-only unary calls, and error mapping to
// calls on the dialed connection (including typed udbclient.Client wrappers).
func (g *GeneratedClient) DialOptions() []grpc.DialOption {
	return []grpc.DialOption{
		grpc.WithChainUnaryInterceptor(g.unaryInterceptor()),
		grpc.WithChainStreamInterceptor(g.streamInterceptor()),
		grpc.WithKeepaliveParams(keepalive.ClientParameters{
			Time:                keepaliveTime,
			Timeout:             keepaliveTimeout,
			PermitWithoutStream: true,
		}),
	}
}

func (g *GeneratedClient) unaryInterceptor() grpc.UnaryClientInterceptor {
	return func(ctx context.Context, method string, req, reply any, cc *grpc.ClientConn, invoker grpc.UnaryInvoker, opts ...grpc.CallOption) error {
		rc := g.opt.Retry
		readOnly := isReadOnlyUnaryRPC(method)
		var lastErr error
		for attempt := 0; attempt < max(1, rc.MaxAttempts); attempt++ {
			if attempt > 0 {
				select {
				case <-time.After(rc.backoff(attempt - 1)):
				case <-ctx.Done():
					return mapError(method, ctx.Err(), nil)
				}
			}
			callCtx, cancel := g.withDeadline(g.outgoingContext(ctx))
			var trailer metadata.MD
			callOpts := append([]grpc.CallOption{grpc.Trailer(&trailer)}, opts...)
			err := invoker(callCtx, method, req, reply, cc, callOpts...)
			cancel()
			if err == nil {
				return nil
			}
			lastErr = mapError(method, err, trailer)
			if !readOnly || !rc.retryableForRPC(status.Code(err), readOnly) {
				return lastErr
			}
		}
		return lastErr
	}
}

func (g *GeneratedClient) streamInterceptor() grpc.StreamClientInterceptor {
	return func(ctx context.Context, desc *grpc.StreamDesc, cc *grpc.ClientConn, method string, streamer grpc.Streamer, opts ...grpc.CallOption) (grpc.ClientStream, error) {
		// Streams are not retried (possibly mid-flight / non-idempotent); we
		// only inject metadata + deadline + map dial errors.
		callCtx, cancel := g.withDeadline(g.outgoingContext(ctx))
		cs, err := streamer(callCtx, desc, cc, method, opts...)
		if err != nil {
			cancel()
			return nil, mapError(method, err, nil)
		}
		return &cancelOnCloseStream{ClientStream: cs, cancel: cancel}, nil
	}
}

// AsError extracts a *Error from any error returned by this layer, if present.
func AsError(err error) (*Error, bool) {
	var e *Error
	if errors.As(err, &e) {
		return e, true
	}
	return nil, false
}

// ── Per-service RPC descriptors ──────────────────────────────────────────────
//
// One RPCInfo per RPC across every service, generated from the proto descriptor
// set. Useful for low-level Invoke/NewStream calls, capability negotiation, and
// observability without hand-listing methods.

// RPCKind classifies an RPC's streaming shape.
type RPCKind string

const (
	KindUnary           RPCKind = "unary"
	KindServerStreaming RPCKind = "server_streaming"
	KindClientStreaming RPCKind = "client_streaming"
	KindBidi            RPCKind = "bidi"
)

// RPCInfo describes a single RPC.
type RPCInfo struct {
	Service       string  // e.g. DataBroker
	ServicePkg    string  // e.g. udb.services.v1
	FullMethod    string  // e.g. /udb.services.v1.DataBroker/Select
	Name          string  // e.g. Select
	Kind          RPCKind // streaming shape
	ReadOnly      bool    // proto EndpointSecurity.operation_kind == READ_ONLY; the
	                      // authoritative retry-safety flag (never guessed from the name)
	OperationKind string  // "read_only" | "mutation" | "destructive"
}

// AllRPCs lists every RPC across every UDB service in this build.
var AllRPCs = []RPCInfo{
	{Service: "AnalyticsService", ServicePkg: "udb.core.analytics.services.v1", FullMethod: "/udb.core.analytics.services.v1.AnalyticsService/GetExecutorPerformance", Name: "GetExecutorPerformance", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AnalyticsService", ServicePkg: "udb.core.analytics.services.v1", FullMethod: "/udb.core.analytics.services.v1.AnalyticsService/GetPipelineSummary", Name: "GetPipelineSummary", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AnalyticsService", ServicePkg: "udb.core.analytics.services.v1", FullMethod: "/udb.core.analytics.services.v1.AnalyticsService/GetReconciliationAnalytics", Name: "GetReconciliationAnalytics", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AnalyticsService", ServicePkg: "udb.core.analytics.services.v1", FullMethod: "/udb.core.analytics.services.v1.AnalyticsService/GetSlaCompliance", Name: "GetSlaCompliance", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AnalyticsService", ServicePkg: "udb.core.analytics.services.v1", FullMethod: "/udb.core.analytics.services.v1.AnalyticsService/GetThroughput", Name: "GetThroughput", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AnalyticsService", ServicePkg: "udb.core.analytics.services.v1", FullMethod: "/udb.core.analytics.services.v1.AnalyticsService/RecordPipelineMetric", Name: "RecordPipelineMetric", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AnalyticsService", ServicePkg: "udb.core.analytics.services.v1", FullMethod: "/udb.core.analytics.services.v1.AnalyticsService/TriggerSnapshot", Name: "TriggerSnapshot", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "ApiKeyService", ServicePkg: "udb.core.apikey.services.v1", FullMethod: "/udb.core.apikey.services.v1.ApiKeyService/CreateApiKey", Name: "CreateApiKey", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "ApiKeyService", ServicePkg: "udb.core.apikey.services.v1", FullMethod: "/udb.core.apikey.services.v1.ApiKeyService/EmergencyRevokeApiKeys", Name: "EmergencyRevokeApiKeys", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "destructive"},
	{Service: "ApiKeyService", ServicePkg: "udb.core.apikey.services.v1", FullMethod: "/udb.core.apikey.services.v1.ApiKeyService/GetApiKey", Name: "GetApiKey", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "ApiKeyService", ServicePkg: "udb.core.apikey.services.v1", FullMethod: "/udb.core.apikey.services.v1.ApiKeyService/GetApiKeyUsageStats", Name: "GetApiKeyUsageStats", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "ApiKeyService", ServicePkg: "udb.core.apikey.services.v1", FullMethod: "/udb.core.apikey.services.v1.ApiKeyService/ListApiKeys", Name: "ListApiKeys", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "ApiKeyService", ServicePkg: "udb.core.apikey.services.v1", FullMethod: "/udb.core.apikey.services.v1.ApiKeyService/RevokeApiKey", Name: "RevokeApiKey", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "ApiKeyService", ServicePkg: "udb.core.apikey.services.v1", FullMethod: "/udb.core.apikey.services.v1.ApiKeyService/RotateApiKey", Name: "RotateApiKey", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "ApiKeyService", ServicePkg: "udb.core.apikey.services.v1", FullMethod: "/udb.core.apikey.services.v1.ApiKeyService/UpdateApiKey", Name: "UpdateApiKey", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "ApiKeyService", ServicePkg: "udb.core.apikey.services.v1", FullMethod: "/udb.core.apikey.services.v1.ApiKeyService/ValidateApiKey", Name: "ValidateApiKey", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AssetService", ServicePkg: "udb.core.asset.services.v1", FullMethod: "/udb.core.asset.services.v1.AssetService/CompleteStep", Name: "CompleteStep", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AssetService", ServicePkg: "udb.core.asset.services.v1", FullMethod: "/udb.core.asset.services.v1.AssetService/CreatePipelineDefinition", Name: "CreatePipelineDefinition", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AssetService", ServicePkg: "udb.core.asset.services.v1", FullMethod: "/udb.core.asset.services.v1.AssetService/GetAsset", Name: "GetAsset", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AssetService", ServicePkg: "udb.core.asset.services.v1", FullMethod: "/udb.core.asset.services.v1.AssetService/GetPipeline", Name: "GetPipeline", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AssetService", ServicePkg: "udb.core.asset.services.v1", FullMethod: "/udb.core.asset.services.v1.AssetService/GetPipelineDefinition", Name: "GetPipelineDefinition", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AssetService", ServicePkg: "udb.core.asset.services.v1", FullMethod: "/udb.core.asset.services.v1.AssetService/ListAssets", Name: "ListAssets", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AssetService", ServicePkg: "udb.core.asset.services.v1", FullMethod: "/udb.core.asset.services.v1.AssetService/RegisterAsset", Name: "RegisterAsset", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AssetService", ServicePkg: "udb.core.asset.services.v1", FullMethod: "/udb.core.asset.services.v1.AssetService/StartPipeline", Name: "StartPipeline", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/AdminResetMfa", Name: "AdminResetMfa", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "destructive"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/AdminResetPassword", Name: "AdminResetPassword", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "destructive"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/AdminRevokeAllTenantSessions", Name: "AdminRevokeAllTenantSessions", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "destructive"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/AdminRevokeAllUserSessions", Name: "AdminRevokeAllUserSessions", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "destructive"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/AdminRevokeSession", Name: "AdminRevokeSession", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "destructive"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/Authenticate", Name: "Authenticate", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/ChangePassword", Name: "ChangePassword", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/ChangeUserStatus", Name: "ChangeUserStatus", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "destructive"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/ConfirmMFAEnrollment", Name: "ConfirmMFAEnrollment", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/CreateSession", Name: "CreateSession", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/CreateUser", Name: "CreateUser", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/DeleteWebAuthnCredential", Name: "DeleteWebAuthnCredential", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/DisableMfaFactor", Name: "DisableMfaFactor", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/EmergencyRevoke", Name: "EmergencyRevoke", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "destructive"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/EnrollMFA", Name: "EnrollMFA", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/FinishWebAuthnAuthentication", Name: "FinishWebAuthnAuthentication", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/FinishWebAuthnRegistration", Name: "FinishWebAuthnRegistration", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/ForgotPassword", Name: "ForgotPassword", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/GenerateRecoveryCodes", Name: "GenerateRecoveryCodes", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/GetJwks", Name: "GetJwks", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/GetMfaPolicy", Name: "GetMfaPolicy", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/GetSession", Name: "GetSession", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/GetUser", Name: "GetUser", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/IntrospectToken", Name: "IntrospectToken", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/IssueMfaChallenge", Name: "IssueMfaChallenge", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/ListDevices", Name: "ListDevices", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/ListMfaFactors", Name: "ListMfaFactors", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/ListSessions", Name: "ListSessions", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/ListUsers", Name: "ListUsers", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/ListWebAuthnCredentials", Name: "ListWebAuthnCredentials", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/Login", Name: "Login", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/Logout", Name: "Logout", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/PutMfaPolicy", Name: "PutMfaPolicy", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/RefreshSession", Name: "RefreshSession", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/RefreshToken", Name: "RefreshToken", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/RenamePasskey", Name: "RenamePasskey", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/ResendOTP", Name: "ResendOTP", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/ResetPassword", Name: "ResetPassword", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/RevokeDevice", Name: "RevokeDevice", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/RevokeRecoveryCodes", Name: "RevokeRecoveryCodes", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/RevokeSession", Name: "RevokeSession", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/SendOTP", Name: "SendOTP", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/SendPhoneVerification", Name: "SendPhoneVerification", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/StartWebAuthnAuthentication", Name: "StartWebAuthnAuthentication", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/StartWebAuthnRegistration", Name: "StartWebAuthnRegistration", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/UpdateUser", Name: "UpdateUser", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/ValidateCSRF", Name: "ValidateCSRF", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/ValidateToken", Name: "ValidateToken", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/VerifyMfaChallenge", Name: "VerifyMfaChallenge", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/VerifyOTP", Name: "VerifyOTP", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/ActivateCanary", Name: "ActivateCanary", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "destructive"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/ActivatePolicyVersion", Name: "ActivatePolicyVersion", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "destructive"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/ApprovePolicyDraft", Name: "ApprovePolicyDraft", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/AssignRole", Name: "AssignRole", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/Authorize", Name: "Authorize", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/BatchCheckPermissions", Name: "BatchCheckPermissions", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/CheckAccess", Name: "CheckAccess", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/CreatePolicyDraft", Name: "CreatePolicyDraft", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/CreatePolicyRule", Name: "CreatePolicyRule", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/CreateRole", Name: "CreateRole", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/DeletePolicyRule", Name: "DeletePolicyRule", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/DeleteRole", Name: "DeleteRole", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/DiffPolicyDraft", Name: "DiffPolicyDraft", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/ExplainPolicy", Name: "ExplainPolicy", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/GetAuthzRevision", Name: "GetAuthzRevision", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/GetCanaryStatus", Name: "GetCanaryStatus", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/GetNativeAccess", Name: "GetNativeAccess", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/GetPolicyBundle", Name: "GetPolicyBundle", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/GetPolicyRule", Name: "GetPolicyRule", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/GetRole", Name: "GetRole", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/InvalidatePolicyBundles", Name: "InvalidatePolicyBundles", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "destructive"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/LintAuthzPolicies", Name: "LintAuthzPolicies", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/ListAccessDecisionAudits", Name: "ListAccessDecisionAudits", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/ListPolicyRules", Name: "ListPolicyRules", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/ListPolicyVersions", Name: "ListPolicyVersions", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/ListRoles", Name: "ListRoles", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/ListUserPermissions", Name: "ListUserPermissions", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/ListUserRoles", Name: "ListUserRoles", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/MigrateLegacyPolicies", Name: "MigrateLegacyPolicies", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "destructive"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/PromoteCanary", Name: "PromoteCanary", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "destructive"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/PutAuthzPolicy", Name: "PutAuthzPolicy", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/PutRelationship", Name: "PutRelationship", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/PutRoleBinding", Name: "PutRoleBinding", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/RejectPolicyDraft", Name: "RejectPolicyDraft", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/RevokeRole", Name: "RevokeRole", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/RollbackPolicyVersion", Name: "RollbackPolicyVersion", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "destructive"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/SeedBuiltinRoles", Name: "SeedBuiltinRoles", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/SimulatePolicy", Name: "SimulatePolicy", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/SubmitPolicyDraft", Name: "SubmitPolicyDraft", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/UpdatePolicyDraft", Name: "UpdatePolicyDraft", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/UpdateRole", Name: "UpdateRole", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "ControlPlaneService", ServicePkg: "udb.core.control.services.v1", FullMethod: "/udb.core.control.services.v1.ControlPlaneService/AckStatus", Name: "AckStatus", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "ControlPlaneService", ServicePkg: "udb.core.control.services.v1", FullMethod: "/udb.core.control.services.v1.ControlPlaneService/DeltaResources", Name: "DeltaResources", Kind: RPCKind("bidi"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "ControlPlaneService", ServicePkg: "udb.core.control.services.v1", FullMethod: "/udb.core.control.services.v1.ControlPlaneService/GetResources", Name: "GetResources", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "ControlPlaneService", ServicePkg: "udb.core.control.services.v1", FullMethod: "/udb.core.control.services.v1.ControlPlaneService/ListNodeStates", Name: "ListNodeStates", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "ControlPlaneService", ServicePkg: "udb.core.control.services.v1", FullMethod: "/udb.core.control.services.v1.ControlPlaneService/StreamResources", Name: "StreamResources", Kind: RPCKind("bidi"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "IdentityProviderService", ServicePkg: "udb.core.idp.services.v1", FullMethod: "/udb.core.idp.services.v1.IdentityProviderService/CreateProvider", Name: "CreateProvider", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "IdentityProviderService", ServicePkg: "udb.core.idp.services.v1", FullMethod: "/udb.core.idp.services.v1.IdentityProviderService/DisableProvider", Name: "DisableProvider", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "IdentityProviderService", ServicePkg: "udb.core.idp.services.v1", FullMethod: "/udb.core.idp.services.v1.IdentityProviderService/ForceJwksRefresh", Name: "ForceJwksRefresh", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "IdentityProviderService", ServicePkg: "udb.core.idp.services.v1", FullMethod: "/udb.core.idp.services.v1.IdentityProviderService/GetProvider", Name: "GetProvider", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "IdentityProviderService", ServicePkg: "udb.core.idp.services.v1", FullMethod: "/udb.core.idp.services.v1.IdentityProviderService/ImportSamlMetadata", Name: "ImportSamlMetadata", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "IdentityProviderService", ServicePkg: "udb.core.idp.services.v1", FullMethod: "/udb.core.idp.services.v1.IdentityProviderService/LinkIdentity", Name: "LinkIdentity", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "IdentityProviderService", ServicePkg: "udb.core.idp.services.v1", FullMethod: "/udb.core.idp.services.v1.IdentityProviderService/ListExternalIdentities", Name: "ListExternalIdentities", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "IdentityProviderService", ServicePkg: "udb.core.idp.services.v1", FullMethod: "/udb.core.idp.services.v1.IdentityProviderService/ListProviders", Name: "ListProviders", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "IdentityProviderService", ServicePkg: "udb.core.idp.services.v1", FullMethod: "/udb.core.idp.services.v1.IdentityProviderService/PreviewClaimMapping", Name: "PreviewClaimMapping", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "IdentityProviderService", ServicePkg: "udb.core.idp.services.v1", FullMethod: "/udb.core.idp.services.v1.IdentityProviderService/PreviewGroupMapping", Name: "PreviewGroupMapping", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "IdentityProviderService", ServicePkg: "udb.core.idp.services.v1", FullMethod: "/udb.core.idp.services.v1.IdentityProviderService/ResolveExternalIdentity", Name: "ResolveExternalIdentity", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "IdentityProviderService", ServicePkg: "udb.core.idp.services.v1", FullMethod: "/udb.core.idp.services.v1.IdentityProviderService/SamlAcs", Name: "SamlAcs", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "IdentityProviderService", ServicePkg: "udb.core.idp.services.v1", FullMethod: "/udb.core.idp.services.v1.IdentityProviderService/ScimCreateGroup", Name: "ScimCreateGroup", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "IdentityProviderService", ServicePkg: "udb.core.idp.services.v1", FullMethod: "/udb.core.idp.services.v1.IdentityProviderService/ScimCreateUser", Name: "ScimCreateUser", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "IdentityProviderService", ServicePkg: "udb.core.idp.services.v1", FullMethod: "/udb.core.idp.services.v1.IdentityProviderService/ScimDeleteGroup", Name: "ScimDeleteGroup", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "IdentityProviderService", ServicePkg: "udb.core.idp.services.v1", FullMethod: "/udb.core.idp.services.v1.IdentityProviderService/ScimDeleteUser", Name: "ScimDeleteUser", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "IdentityProviderService", ServicePkg: "udb.core.idp.services.v1", FullMethod: "/udb.core.idp.services.v1.IdentityProviderService/ScimGetGroup", Name: "ScimGetGroup", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "IdentityProviderService", ServicePkg: "udb.core.idp.services.v1", FullMethod: "/udb.core.idp.services.v1.IdentityProviderService/ScimGetUser", Name: "ScimGetUser", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "IdentityProviderService", ServicePkg: "udb.core.idp.services.v1", FullMethod: "/udb.core.idp.services.v1.IdentityProviderService/ScimListGroups", Name: "ScimListGroups", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "IdentityProviderService", ServicePkg: "udb.core.idp.services.v1", FullMethod: "/udb.core.idp.services.v1.IdentityProviderService/ScimListUsers", Name: "ScimListUsers", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "IdentityProviderService", ServicePkg: "udb.core.idp.services.v1", FullMethod: "/udb.core.idp.services.v1.IdentityProviderService/ScimPatchGroup", Name: "ScimPatchGroup", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "IdentityProviderService", ServicePkg: "udb.core.idp.services.v1", FullMethod: "/udb.core.idp.services.v1.IdentityProviderService/ScimPatchUser", Name: "ScimPatchUser", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "IdentityProviderService", ServicePkg: "udb.core.idp.services.v1", FullMethod: "/udb.core.idp.services.v1.IdentityProviderService/ScimReplaceUser", Name: "ScimReplaceUser", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "IdentityProviderService", ServicePkg: "udb.core.idp.services.v1", FullMethod: "/udb.core.idp.services.v1.IdentityProviderService/StartSamlLogin", Name: "StartSamlLogin", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "IdentityProviderService", ServicePkg: "udb.core.idp.services.v1", FullMethod: "/udb.core.idp.services.v1.IdentityProviderService/TestProviderDiscovery", Name: "TestProviderDiscovery", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "IdentityProviderService", ServicePkg: "udb.core.idp.services.v1", FullMethod: "/udb.core.idp.services.v1.IdentityProviderService/UnlinkIdentity", Name: "UnlinkIdentity", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "IdentityProviderService", ServicePkg: "udb.core.idp.services.v1", FullMethod: "/udb.core.idp.services.v1.IdentityProviderService/UpdateProvider", Name: "UpdateProvider", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "NotificationService", ServicePkg: "udb.core.notification.services.v1", FullMethod: "/udb.core.notification.services.v1.NotificationService/GetDeliveryStats", Name: "GetDeliveryStats", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "NotificationService", ServicePkg: "udb.core.notification.services.v1", FullMethod: "/udb.core.notification.services.v1.NotificationService/GetNotification", Name: "GetNotification", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "NotificationService", ServicePkg: "udb.core.notification.services.v1", FullMethod: "/udb.core.notification.services.v1.NotificationService/GetPreference", Name: "GetPreference", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "NotificationService", ServicePkg: "udb.core.notification.services.v1", FullMethod: "/udb.core.notification.services.v1.NotificationService/GetTemplate", Name: "GetTemplate", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "NotificationService", ServicePkg: "udb.core.notification.services.v1", FullMethod: "/udb.core.notification.services.v1.NotificationService/ListNotifications", Name: "ListNotifications", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "NotificationService", ServicePkg: "udb.core.notification.services.v1", FullMethod: "/udb.core.notification.services.v1.NotificationService/ListPreferences", Name: "ListPreferences", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "NotificationService", ServicePkg: "udb.core.notification.services.v1", FullMethod: "/udb.core.notification.services.v1.NotificationService/ListTemplates", Name: "ListTemplates", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "NotificationService", ServicePkg: "udb.core.notification.services.v1", FullMethod: "/udb.core.notification.services.v1.NotificationService/RetryNotification", Name: "RetryNotification", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "NotificationService", ServicePkg: "udb.core.notification.services.v1", FullMethod: "/udb.core.notification.services.v1.NotificationService/SendNotification", Name: "SendNotification", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "NotificationService", ServicePkg: "udb.core.notification.services.v1", FullMethod: "/udb.core.notification.services.v1.NotificationService/SetPreference", Name: "SetPreference", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "NotificationService", ServicePkg: "udb.core.notification.services.v1", FullMethod: "/udb.core.notification.services.v1.NotificationService/UpsertTemplate", Name: "UpsertTemplate", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "StorageService", ServicePkg: "udb.core.storage.services.v1", FullMethod: "/udb.core.storage.services.v1.StorageService/DeleteFile", Name: "DeleteFile", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "StorageService", ServicePkg: "udb.core.storage.services.v1", FullMethod: "/udb.core.storage.services.v1.StorageService/FinalizeUpload", Name: "FinalizeUpload", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "StorageService", ServicePkg: "udb.core.storage.services.v1", FullMethod: "/udb.core.storage.services.v1.StorageService/GetDownloadUrl", Name: "GetDownloadUrl", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "StorageService", ServicePkg: "udb.core.storage.services.v1", FullMethod: "/udb.core.storage.services.v1.StorageService/GetFile", Name: "GetFile", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "StorageService", ServicePkg: "udb.core.storage.services.v1", FullMethod: "/udb.core.storage.services.v1.StorageService/ListFiles", Name: "ListFiles", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "StorageService", ServicePkg: "udb.core.storage.services.v1", FullMethod: "/udb.core.storage.services.v1.StorageService/RegisterUpload", Name: "RegisterUpload", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "StorageService", ServicePkg: "udb.core.storage.services.v1", FullMethod: "/udb.core.storage.services.v1.StorageService/UpdateFile", Name: "UpdateFile", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "TenantService", ServicePkg: "udb.core.tenant.services.v1", FullMethod: "/udb.core.tenant.services.v1.TenantService/CreateTenant", Name: "CreateTenant", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "TenantService", ServicePkg: "udb.core.tenant.services.v1", FullMethod: "/udb.core.tenant.services.v1.TenantService/GetTenant", Name: "GetTenant", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "TenantService", ServicePkg: "udb.core.tenant.services.v1", FullMethod: "/udb.core.tenant.services.v1.TenantService/GetTenantConfig", Name: "GetTenantConfig", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "TenantService", ServicePkg: "udb.core.tenant.services.v1", FullMethod: "/udb.core.tenant.services.v1.TenantService/ListTenants", Name: "ListTenants", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "TenantService", ServicePkg: "udb.core.tenant.services.v1", FullMethod: "/udb.core.tenant.services.v1.TenantService/UpdateTenant", Name: "UpdateTenant", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "TenantService", ServicePkg: "udb.core.tenant.services.v1", FullMethod: "/udb.core.tenant.services.v1.TenantService/UpdateTenantConfig", Name: "UpdateTenantConfig", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "PeerService", ServicePkg: "udb.core.webrtc.services.v1", FullMethod: "/udb.core.webrtc.services.v1.PeerService/GetPeer", Name: "GetPeer", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "PeerService", ServicePkg: "udb.core.webrtc.services.v1", FullMethod: "/udb.core.webrtc.services.v1.PeerService/JoinRoom", Name: "JoinRoom", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "PeerService", ServicePkg: "udb.core.webrtc.services.v1", FullMethod: "/udb.core.webrtc.services.v1.PeerService/LeaveRoom", Name: "LeaveRoom", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "PeerService", ServicePkg: "udb.core.webrtc.services.v1", FullMethod: "/udb.core.webrtc.services.v1.PeerService/ListPeers", Name: "ListPeers", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "RoomService", ServicePkg: "udb.core.webrtc.services.v1", FullMethod: "/udb.core.webrtc.services.v1.RoomService/CloseRoom", Name: "CloseRoom", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "RoomService", ServicePkg: "udb.core.webrtc.services.v1", FullMethod: "/udb.core.webrtc.services.v1.RoomService/CreateRoom", Name: "CreateRoom", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "RoomService", ServicePkg: "udb.core.webrtc.services.v1", FullMethod: "/udb.core.webrtc.services.v1.RoomService/GetRoom", Name: "GetRoom", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "RoomService", ServicePkg: "udb.core.webrtc.services.v1", FullMethod: "/udb.core.webrtc.services.v1.RoomService/ListRooms", Name: "ListRooms", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "RoomService", ServicePkg: "udb.core.webrtc.services.v1", FullMethod: "/udb.core.webrtc.services.v1.RoomService/UpdateRoom", Name: "UpdateRoom", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "SignalingService", ServicePkg: "udb.core.webrtc.services.v1", FullMethod: "/udb.core.webrtc.services.v1.SignalingService/Signal", Name: "Signal", Kind: RPCKind("bidi"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "TrackService", ServicePkg: "udb.core.webrtc.services.v1", FullMethod: "/udb.core.webrtc.services.v1.TrackService/ListTracks", Name: "ListTracks", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "TrackService", ServicePkg: "udb.core.webrtc.services.v1", FullMethod: "/udb.core.webrtc.services.v1.TrackService/MuteTrack", Name: "MuteTrack", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "TrackService", ServicePkg: "udb.core.webrtc.services.v1", FullMethod: "/udb.core.webrtc.services.v1.TrackService/PublishTrack", Name: "PublishTrack", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "TrackService", ServicePkg: "udb.core.webrtc.services.v1", FullMethod: "/udb.core.webrtc.services.v1.TrackService/UnpublishTrack", Name: "UnpublishTrack", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "TurnService", ServicePkg: "udb.core.webrtc.services.v1", FullMethod: "/udb.core.webrtc.services.v1.TurnService/IssueCredentials", Name: "IssueCredentials", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/ActivateCatalog", Name: "ActivateCatalog", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "destructive"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/AnalyticalQuery", Name: "AnalyticalQuery", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/ApplyMigration", Name: "ApplyMigration", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/ApproveMigrationPlan", Name: "ApproveMigrationPlan", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/BatchSelect", Name: "BatchSelect", Kind: RPCKind("bidi"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/BatchUpsert", Name: "BatchUpsert", Kind: RPCKind("bidi"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/BeginTx", Name: "BeginTx", Kind: RPCKind("bidi"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/CacheDelete", Name: "CacheDelete", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/CacheGet", Name: "CacheGet", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/CacheScan", Name: "CacheScan", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/CacheSet", Name: "CacheSet", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/CreateMaterializedView", Name: "CreateMaterializedView", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/Delete", Name: "Delete", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/DeletePolicy", Name: "DeletePolicy", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/DismissDlqEvent", Name: "DismissDlqEvent", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/DocumentDelete", Name: "DocumentDelete", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/DocumentFind", Name: "DocumentFind", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/DocumentGet", Name: "DocumentGet", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/DocumentUpsert", Name: "DocumentUpsert", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/DropResource", Name: "DropResource", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "destructive"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/EnqueueOutboxEvent", Name: "EnqueueOutboxEvent", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/EnsureProject", Name: "EnsureProject", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/EnsureResource", Name: "EnsureResource", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/GeneratePresignedUrl", Name: "GeneratePresignedUrl", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/GenericDispatch", Name: "GenericDispatch", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/GetAdminSummary", Name: "GetAdminSummary", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/GetCapabilities", Name: "GetCapabilities", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/GetCatalogManifest", Name: "GetCatalogManifest", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/GetCatalogVersion", Name: "GetCatalogVersion", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/GetCatalogVersions", Name: "GetCatalogVersions", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/GetCdcStatus", Name: "GetCdcStatus", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/GetDlqEvent", Name: "GetDlqEvent", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/GetHealthReport", Name: "GetHealthReport", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/GetMigrationStatus", Name: "GetMigrationStatus", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/GetObject", Name: "GetObject", Kind: RPCKind("server_streaming"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/GetSaga", Name: "GetSaga", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/GraphMutate", Name: "GraphMutate", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/GraphQuery", Name: "GraphQuery", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/InitiateMultipartUpload", Name: "InitiateMultipartUpload", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/LintPolicies", Name: "LintPolicies", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/ListAdminAuditLogs", Name: "ListAdminAuditLogs", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/ListDlqEvents", Name: "ListDlqEvents", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/ListMessageSchemas", Name: "ListMessageSchemas", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/ListMigrationRuns", Name: "ListMigrationRuns", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/ListPolicies", Name: "ListPolicies", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/ListProjects", Name: "ListProjects", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/ListResources", Name: "ListResources", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/ListSagas", Name: "ListSagas", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/LookupMessageSchema", Name: "LookupMessageSchema", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/MarkSagaReviewed", Name: "MarkSagaReviewed", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/PauseCdc", Name: "PauseCdc", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/PlanMigration", Name: "PlanMigration", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/PreviewCdcRedaction", Name: "PreviewCdcRedaction", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/PublishCDC", Name: "PublishCDC", Kind: RPCKind("server_streaming"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/PutObject", Name: "PutObject", Kind: RPCKind("client_streaming"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/PutPolicy", Name: "PutPolicy", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "destructive"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/QuarantineDlqEvent", Name: "QuarantineDlqEvent", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/ReloadPolicies", Name: "ReloadPolicies", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "destructive"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/ReplayDlqEvent", Name: "ReplayDlqEvent", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/ResumeCdc", Name: "ResumeCdc", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/RetrySagaCompensation", Name: "RetrySagaCompensation", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/RollbackCatalog", Name: "RollbackCatalog", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "destructive"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/ScanProjectionDrift", Name: "ScanProjectionDrift", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/Select", Name: "Select", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/SelectV2", Name: "SelectV2", Kind: RPCKind("server_streaming"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/StageCatalog", Name: "StageCatalog", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "destructive"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/StepDownCdcLeader", Name: "StepDownCdcLeader", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/TimeSeriesQuery", Name: "TimeSeriesQuery", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/TimeSeriesWrite", Name: "TimeSeriesWrite", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/Upsert", Name: "Upsert", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/ValidateCatalog", Name: "ValidateCatalog", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "destructive"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/VectorBatchUpsert", Name: "VectorBatchUpsert", Kind: RPCKind("bidi"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/VectorHybridSearch", Name: "VectorHybridSearch", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/VectorSearch", Name: "VectorSearch", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/VectorUpsert", Name: "VectorUpsert", Kind: RPCKind("unary"), ReadOnly: false, OperationKind: "mutation"},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/VerifyAdminAuditLog", Name: "VerifyAdminAuditLog", Kind: RPCKind("unary"), ReadOnly: true, OperationKind: "read_only"},
}

// ServiceRPCCounts maps each service's full name to its RPC count.
var ServiceRPCCounts = map[string]int{
	"udb.core.analytics.services.v1.AnalyticsService": 7,
	"udb.core.apikey.services.v1.ApiKeyService": 9,
	"udb.core.asset.services.v1.AssetService": 8,
	"udb.core.authn.services.v1.AuthnService": 50,
	"udb.core.authz.services.v1.AuthzService": 41,
	"udb.core.control.services.v1.ControlPlaneService": 5,
	"udb.core.idp.services.v1.IdentityProviderService": 27,
	"udb.core.notification.services.v1.NotificationService": 11,
	"udb.core.storage.services.v1.StorageService": 7,
	"udb.core.tenant.services.v1.TenantService": 6,
	"udb.core.webrtc.services.v1.PeerService": 4,
	"udb.core.webrtc.services.v1.RoomService": 5,
	"udb.core.webrtc.services.v1.SignalingService": 1,
	"udb.core.webrtc.services.v1.TrackService": 4,
	"udb.core.webrtc.services.v1.TurnService": 1,
	"udb.services.v1.DataBroker": 76,
}

// rpcIndex is a fast Name->RPCInfo lookup built from AllRPCs at init.
var rpcIndex = func() map[string]RPCInfo {
	m := make(map[string]RPCInfo, len(AllRPCs))
	for _, r := range AllRPCs {
		m[r.Name] = r
		m[r.FullMethod] = r
	}
	return m
}()

// LookupRPC finds an RPC by short name (e.g. "Select") or full method path.
func LookupRPC(nameOrPath string) (RPCInfo, bool) {
	r, ok := rpcIndex[nameOrPath]
	return r, ok
}

// isReadOnlyUnaryRPC reports whether a unary RPC is safe to auto-retry. It reads
// the proto-derived `ReadOnly` flag (EndpointSecurity.operation_kind) — the single
// source of truth — and never inspects the method name.
func isReadOnlyUnaryRPC(method string) bool {
	r, ok := LookupRPC(method)
	if !ok {
		return false
	}
	return r.Kind == KindUnary && r.ReadOnly
}

func init() {
	if GeneratedProtocolVersion != ProtocolVersion {
		// Guard against a stale hand-written ProtocolVersion drifting from the
		// generated wire version. Generation keeps them aligned.
		panic(fmt.Sprintf(
			"udbclient: generated protocol version %q != hand-written ProtocolVersion %q; regenerate the SDK",
			GeneratedProtocolVersion, ProtocolVersion))
	}
}
