package udbclient

// Generated by `udb sdk generate` from the embedded proto descriptor set. Edit the template under sdk-templates/<lang>/, not this file.
//
// generated_client.go is a GENERATED robustness / forwarding layer that COMPOSES
// WITH the hand-written udbclient package (client.go, auth*.go, negotiation.go).
// It NEVER replaces them. It adds, on top of the existing buf-generated gRPC
// stubs:
//
//   - configurable per-call deadline / timeout
//   - retry with exponential backoff + jitter on transient gRPC codes
//     (UNAVAILABLE, DEADLINE_EXCEEDED, RESOURCE_EXHAUSTED), never retrying
//     non-idempotent client-streaming / bidi RPCs
//   - TLS / credential wiring (via the dial options you pass)
//   - metadata injection (the same 8 UDB headers as Client.Context, plus
//     authorization / api-key / request-id)
//   - typed error mapping (unpacks the `udb-error-detail-bin` trailer into a
//     typed *Error, else a clean error)
//
// It deliberately speaks the gRPC wire generically through
// grpc.ClientConnInterface.Invoke / NewStream keyed on each RPC's full method
// path, so it needs NO per-message Go type imports and stays valid as the proto
// surface grows. To make a fully typed call, keep using the hand-written
// udbclient.Client / udbclient.AuthClient wrappers — this layer governs the
// connection (interceptors) those wrappers run on, plus low-level escape
// hatches for RPCs that don't yet have a typed helper.
//
// Covers 153 RPCs across 7 services
// (UDB v0.3.1, wire protocol 1.0.0).

import (
	"context"
	"errors"
	"fmt"
	"math"
	"math/rand"
	"time"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
)

// SDKVersion is the UDB release this generated layer was rendered from. It is
// baked at generation time and is the version the bundled `udb` CLI launcher
// (cmd/udb) will resolve.
const SDKVersion = "0.3.1"

// GeneratedProtocolVersion mirrors the wire protocol this layer targets. It is
// the generated companion to the hand-written udbclient.ProtocolVersion and is
// kept identical; both are asserted equal at package init below.
const GeneratedProtocolVersion = "1.0.0"

// errorDetailTrailer is the binary gRPC trailer the broker sets to a serialized
// udb.entity.v1.ErrorDetail. We surface it on *Error without depending on the
// generated message type (callers that want the decoded proto can unmarshal
// Error.DetailBin themselves).
const errorDetailTrailer = "udb-error-detail-bin"

// RetryConfig controls the backoff retry behavior of the generated wrappers.
// The zero value is unusable; use DefaultRetryConfig().
type RetryConfig struct {
	MaxAttempts  int           // total tries including the first; <=1 disables retry
	BaseBackoff  time.Duration // backoff for the first retry
	MaxBackoff   time.Duration // backoff ceiling
	Jitter       float64       // 0..1 fraction of randomized jitter added to each backoff
	RetryOnCodes []codes.Code  // transient codes considered retryable
}

// DefaultRetryConfig returns the proven UDB defaults: 4 attempts, 100ms base,
// 5s ceiling, full jitter, retrying only safe transient codes.
func DefaultRetryConfig() RetryConfig {
	return RetryConfig{
		MaxAttempts: 4,
		BaseBackoff: 100 * time.Millisecond,
		MaxBackoff:  5 * time.Second,
		Jitter:      1.0,
		RetryOnCodes: []codes.Code{
			codes.Unavailable,
			codes.DeadlineExceeded,
			codes.ResourceExhausted,
		},
	}
}

func (rc RetryConfig) retryable(code codes.Code) bool {
	for _, c := range rc.RetryOnCodes {
		if c == code {
			return true
		}
	}
	return false
}

func (rc RetryConfig) backoff(attempt int) time.Duration {
	// attempt is 0-based for the first *retry*.
	d := float64(rc.BaseBackoff) * math.Pow(2, float64(attempt))
	if d > float64(rc.MaxBackoff) {
		d = float64(rc.MaxBackoff)
	}
	if rc.Jitter > 0 {
		j := d * rc.Jitter * rand.Float64()
		d = d - (d * rc.Jitter) + j
		if d < 0 {
			d = 0
		}
	}
	return time.Duration(d)
}

// Error is the typed error the generated layer maps gRPC failures to. It always
// carries the gRPC code/message; when the broker attached a serialized
// ErrorDetail trailer, DetailBin holds its raw bytes for the caller to decode.
type Error struct {
	Code      codes.Code
	Message   string
	RPC       string // full method path, e.g. /udb.services.v1.DataBroker/Select
	DetailBin []byte // raw udb.entity.v1.ErrorDetail bytes, or nil
	cause     error
}

func (e *Error) Error() string {
	if len(e.DetailBin) > 0 {
		return fmt.Sprintf("udb %s: %s (%s) [+error-detail %dB]", e.RPC, e.Message, e.Code, len(e.DetailBin))
	}
	return fmt.Sprintf("udb %s: %s (%s)", e.RPC, e.Message, e.Code)
}

func (e *Error) Unwrap() error { return e.cause }

// mapError converts a gRPC error (with optional trailer metadata) into *Error.
// A nil err returns nil.
func mapError(rpcPath string, err error, trailer metadata.MD) error {
	if err == nil {
		return nil
	}
	st, _ := status.FromError(err)
	out := &Error{
		Code:    st.Code(),
		Message: st.Message(),
		RPC:     rpcPath,
		cause:   err,
	}
	if vals := trailer.Get(errorDetailTrailer); len(vals) > 0 {
		out.DetailBin = []byte(vals[len(vals)-1])
	}
	return out
}

// Options configures a GeneratedClient.
type Options struct {
	// Meta is attached as the 8 UDB headers on every outgoing call, exactly as
	// the hand-written Client.Context does.
	Meta Metadata
	// CallTimeout, when > 0, is applied as a per-call deadline if the caller's
	// context has none.
	CallTimeout time.Duration
	// Retry governs backoff retries. Defaults to DefaultRetryConfig() when zero.
	Retry RetryConfig
	// Authorization, when non-empty, is sent as the `authorization` header
	// (e.g. "Bearer <jwt>").
	Authorization string
	// APIKey, when non-empty, is sent as the `x-api-key` header.
	APIKey string
	// RequestID, when non-empty, is sent as the `x-request-id` header. When
	// empty a per-call id is derived from Meta.CorrelationID if set.
	RequestID string
}

func (o Options) withDefaults() Options {
	if o.Retry.MaxAttempts == 0 {
		o.Retry = DefaultRetryConfig()
	}
	return o
}

// GeneratedClient is the robustness layer. It holds a gRPC connection and the
// options applied to every wrapped call. Build it from an existing
// *grpc.ClientConn (so TLS / credentials / dial options are entirely yours),
// then either:
//
//   - use the hand-written typed wrappers (udbclient.New(gc.Conn(), meta), …)
//     which inherit nothing extra, OR
//   - dial through DialOptions() so the retry/metadata/error interceptors apply
//     to those typed wrappers automatically, OR
//   - call gc.InvokeUnary / gc.NewServerStream / gc.NewClientStream for RPCs
//     without a typed helper.
type GeneratedClient struct {
	conn grpc.ClientConnInterface
	opt  Options
}

// NewGenerated wraps an existing connection. The connection's transport
// security (TLS/insecure) and credentials are whatever you configured when you
// dialed it; this layer never downgrades them.
func NewGenerated(conn grpc.ClientConnInterface, opt Options) *GeneratedClient {
	return &GeneratedClient{conn: conn, opt: opt.withDefaults()}
}

// Conn exposes the underlying connection so the hand-written typed wrappers can
// be built on the same channel: udbclient.New(gc.Conn(), gc.Meta()).
func (g *GeneratedClient) Conn() grpc.ClientConnInterface { return g.conn }

// Meta returns the configured caller Metadata.
func (g *GeneratedClient) Meta() Metadata { return g.opt.Meta }

// outgoingContext attaches the 8 UDB headers plus optional auth / api-key /
// request-id, reusing joinScopes from the hand-written client.go.
func (g *GeneratedClient) outgoingContext(ctx context.Context) context.Context {
	m := g.opt.Meta
	pairs := []string{
		"x-tenant-id", m.TenantID,
		"x-user-id", m.UserID,
		"x-purpose", m.Purpose,
		"x-correlation-id", m.CorrelationID,
		"x-service-identity", m.ServiceIdentity,
		"x-udb-project-id", m.ProjectID,
		"x-udb-client-catalog-version", m.ClientCatalogVersion,
	}
	if len(m.Scopes) > 0 {
		pairs = append(pairs, "x-scopes", joinScopes(m.Scopes))
	}
	if g.opt.Authorization != "" {
		pairs = append(pairs, "authorization", g.opt.Authorization)
	}
	if g.opt.APIKey != "" {
		pairs = append(pairs, "x-api-key", g.opt.APIKey)
	}
	if rid := g.opt.RequestID; rid != "" {
		pairs = append(pairs, "x-request-id", rid)
	} else if m.CorrelationID != "" {
		pairs = append(pairs, "x-request-id", m.CorrelationID)
	}
	return metadata.AppendToOutgoingContext(ctx, pairs...)
}

func (g *GeneratedClient) withDeadline(ctx context.Context) (context.Context, context.CancelFunc) {
	if g.opt.CallTimeout <= 0 {
		return ctx, func() {}
	}
	if _, ok := ctx.Deadline(); ok {
		return ctx, func() {}
	}
	return context.WithTimeout(ctx, g.opt.CallTimeout)
}

// InvokeUnary performs a unary RPC by full method path with metadata injection,
// per-call deadline, retry with backoff, and typed error mapping. req/reply are
// proto.Message values (the generated request/response types from ./gen). This
// is the engine the typed wrappers below delegate to.
func (g *GeneratedClient) InvokeUnary(ctx context.Context, fullMethod string, req, reply any, opts ...grpc.CallOption) error {
	rc := g.opt.Retry
	var lastErr error
	for attempt := 0; attempt < max(1, rc.MaxAttempts); attempt++ {
		if attempt > 0 {
			select {
			case <-time.After(rc.backoff(attempt - 1)):
			case <-ctx.Done():
				return mapError(fullMethod, ctx.Err(), nil)
			}
		}
		callCtx, cancel := g.withDeadline(g.outgoingContext(ctx))
		var trailer metadata.MD
		callOpts := append([]grpc.CallOption{grpc.Trailer(&trailer)}, opts...)
		err := g.conn.Invoke(callCtx, fullMethod, req, reply, callOpts...)
		cancel()
		if err == nil {
			return nil
		}
		lastErr = mapError(fullMethod, err, trailer)
		if !rc.retryable(status.Code(err)) {
			return lastErr
		}
	}
	return lastErr
}

// NewServerStream opens a server-streaming RPC. Streaming RPCs are NOT retried
// here (the stream may have already produced data); retry is the caller's
// decision. Metadata and per-call deadline still apply.
func (g *GeneratedClient) NewServerStream(ctx context.Context, fullMethod string, desc *grpc.StreamDesc, req any, opts ...grpc.CallOption) (grpc.ClientStream, error) {
	callCtx, cancel := g.withDeadline(g.outgoingContext(ctx))
	cs, err := g.conn.NewStream(callCtx, desc, fullMethod, opts...)
	if err != nil {
		cancel()
		return nil, mapError(fullMethod, err, nil)
	}
	if req != nil {
		if err := cs.SendMsg(req); err != nil {
			cancel()
			return nil, mapError(fullMethod, err, nil)
		}
		if err := cs.CloseSend(); err != nil {
			cancel()
			return nil, mapError(fullMethod, err, nil)
		}
	}
	return &cancelOnRecvStream{ClientStream: cs, cancel: cancel}, nil
}

// NewClientStream opens a client-streaming or bidi RPC. Never retried (the body
// is non-idempotent). Metadata and per-call deadline still apply.
func (g *GeneratedClient) NewClientStream(ctx context.Context, fullMethod string, desc *grpc.StreamDesc, opts ...grpc.CallOption) (grpc.ClientStream, error) {
	callCtx, cancel := g.withDeadline(g.outgoingContext(ctx))
	cs, err := g.conn.NewStream(callCtx, desc, fullMethod, opts...)
	if err != nil {
		cancel()
		return nil, mapError(fullMethod, err, nil)
	}
	return &cancelOnCloseStream{ClientStream: cs, cancel: cancel}, nil
}

type cancelOnRecvStream struct {
	grpc.ClientStream
	cancel context.CancelFunc
}

func (s *cancelOnRecvStream) RecvMsg(m any) error {
	err := s.ClientStream.RecvMsg(m)
	if err != nil {
		s.cancel()
	}
	return err
}

type cancelOnCloseStream struct {
	grpc.ClientStream
	cancel context.CancelFunc
}

func (s *cancelOnCloseStream) RecvMsg(m any) error {
	err := s.ClientStream.RecvMsg(m)
	if err != nil {
		s.cancel()
	}
	return err
}

func (s *cancelOnCloseStream) CloseSend() error {
	err := s.ClientStream.CloseSend()
	s.cancel()
	return err
}

// ── Dial-option interceptors ─────────────────────────────────────────────────
//
// Prefer these when you want the typed hand-written wrappers (Client, AuthClient)
// to gain retry/metadata/error-mapping transparently. Pass them to
// grpc.NewClient(target, append(yourSecurityOpts, gc.DialOptions()...)...).

// DialOptions returns the unary + stream interceptors that apply this client's
// metadata, deadline, retry, and error mapping to ANY call on the dialed
// connection (including the typed udbclient.Client wrappers).
func (g *GeneratedClient) DialOptions() []grpc.DialOption {
	return []grpc.DialOption{
		grpc.WithChainUnaryInterceptor(g.unaryInterceptor()),
		grpc.WithChainStreamInterceptor(g.streamInterceptor()),
	}
}

func (g *GeneratedClient) unaryInterceptor() grpc.UnaryClientInterceptor {
	return func(ctx context.Context, method string, req, reply any, cc *grpc.ClientConn, invoker grpc.UnaryInvoker, opts ...grpc.CallOption) error {
		rc := g.opt.Retry
		var lastErr error
		for attempt := 0; attempt < max(1, rc.MaxAttempts); attempt++ {
			if attempt > 0 {
				select {
				case <-time.After(rc.backoff(attempt - 1)):
				case <-ctx.Done():
					return mapError(method, ctx.Err(), nil)
				}
			}
			callCtx, cancel := g.withDeadline(g.outgoingContext(ctx))
			var trailer metadata.MD
			callOpts := append([]grpc.CallOption{grpc.Trailer(&trailer)}, opts...)
			err := invoker(callCtx, method, req, reply, cc, callOpts...)
			cancel()
			if err == nil {
				return nil
			}
			lastErr = mapError(method, err, trailer)
			if !rc.retryable(status.Code(err)) {
				return lastErr
			}
		}
		return lastErr
	}
}

func (g *GeneratedClient) streamInterceptor() grpc.StreamClientInterceptor {
	return func(ctx context.Context, desc *grpc.StreamDesc, cc *grpc.ClientConn, method string, streamer grpc.Streamer, opts ...grpc.CallOption) (grpc.ClientStream, error) {
		// Streams are not retried (possibly mid-flight / non-idempotent); we
		// only inject metadata + deadline + map dial errors.
		callCtx, cancel := g.withDeadline(g.outgoingContext(ctx))
		cs, err := streamer(callCtx, desc, cc, method, opts...)
		if err != nil {
			cancel()
			return nil, mapError(method, err, nil)
		}
		return &cancelOnCloseStream{ClientStream: cs, cancel: cancel}, nil
	}
}

// AsError extracts a *Error from any error returned by this layer, if present.
func AsError(err error) (*Error, bool) {
	var e *Error
	if errors.As(err, &e) {
		return e, true
	}
	return nil, false
}

// ── Per-service RPC descriptors ──────────────────────────────────────────────
//
// One RPCInfo per RPC across every service, generated from the proto descriptor
// set. Useful for low-level Invoke/NewStream calls, capability negotiation, and
// observability without hand-listing methods.

// RPCKind classifies an RPC's streaming shape.
type RPCKind string

const (
	KindUnary           RPCKind = "unary"
	KindServerStreaming RPCKind = "server_streaming"
	KindClientStreaming RPCKind = "client_streaming"
	KindBidi            RPCKind = "bidi"
)

// RPCInfo describes a single RPC.
type RPCInfo struct {
	Service    string  // e.g. DataBroker
	ServicePkg string  // e.g. udb.services.v1
	FullMethod string  // e.g. /udb.services.v1.DataBroker/Select
	Name       string  // e.g. Select
	Kind       RPCKind // streaming shape
}

// AllRPCs lists every RPC across every UDB service in this build.
var AllRPCs = []RPCInfo{
	{Service: "AnalyticsService", ServicePkg: "udb.core.analytics.services.v1", FullMethod: "/udb.core.analytics.services.v1.AnalyticsService/GetExecutorPerformance", Name: "GetExecutorPerformance", Kind: RPCKind("unary")},
	{Service: "AnalyticsService", ServicePkg: "udb.core.analytics.services.v1", FullMethod: "/udb.core.analytics.services.v1.AnalyticsService/GetPipelineSummary", Name: "GetPipelineSummary", Kind: RPCKind("unary")},
	{Service: "AnalyticsService", ServicePkg: "udb.core.analytics.services.v1", FullMethod: "/udb.core.analytics.services.v1.AnalyticsService/GetReconciliationAnalytics", Name: "GetReconciliationAnalytics", Kind: RPCKind("unary")},
	{Service: "AnalyticsService", ServicePkg: "udb.core.analytics.services.v1", FullMethod: "/udb.core.analytics.services.v1.AnalyticsService/GetSlaCompliance", Name: "GetSlaCompliance", Kind: RPCKind("unary")},
	{Service: "AnalyticsService", ServicePkg: "udb.core.analytics.services.v1", FullMethod: "/udb.core.analytics.services.v1.AnalyticsService/GetThroughput", Name: "GetThroughput", Kind: RPCKind("unary")},
	{Service: "AnalyticsService", ServicePkg: "udb.core.analytics.services.v1", FullMethod: "/udb.core.analytics.services.v1.AnalyticsService/RecordPipelineMetric", Name: "RecordPipelineMetric", Kind: RPCKind("unary")},
	{Service: "AnalyticsService", ServicePkg: "udb.core.analytics.services.v1", FullMethod: "/udb.core.analytics.services.v1.AnalyticsService/TriggerSnapshot", Name: "TriggerSnapshot", Kind: RPCKind("unary")},
	{Service: "ApiKeyService", ServicePkg: "udb.core.apikey.services.v1", FullMethod: "/udb.core.apikey.services.v1.ApiKeyService/CreateApiKey", Name: "CreateApiKey", Kind: RPCKind("unary")},
	{Service: "ApiKeyService", ServicePkg: "udb.core.apikey.services.v1", FullMethod: "/udb.core.apikey.services.v1.ApiKeyService/GetApiKey", Name: "GetApiKey", Kind: RPCKind("unary")},
	{Service: "ApiKeyService", ServicePkg: "udb.core.apikey.services.v1", FullMethod: "/udb.core.apikey.services.v1.ApiKeyService/GetApiKeyUsageStats", Name: "GetApiKeyUsageStats", Kind: RPCKind("unary")},
	{Service: "ApiKeyService", ServicePkg: "udb.core.apikey.services.v1", FullMethod: "/udb.core.apikey.services.v1.ApiKeyService/ListApiKeys", Name: "ListApiKeys", Kind: RPCKind("unary")},
	{Service: "ApiKeyService", ServicePkg: "udb.core.apikey.services.v1", FullMethod: "/udb.core.apikey.services.v1.ApiKeyService/RevokeApiKey", Name: "RevokeApiKey", Kind: RPCKind("unary")},
	{Service: "ApiKeyService", ServicePkg: "udb.core.apikey.services.v1", FullMethod: "/udb.core.apikey.services.v1.ApiKeyService/UpdateApiKey", Name: "UpdateApiKey", Kind: RPCKind("unary")},
	{Service: "ApiKeyService", ServicePkg: "udb.core.apikey.services.v1", FullMethod: "/udb.core.apikey.services.v1.ApiKeyService/ValidateApiKey", Name: "ValidateApiKey", Kind: RPCKind("unary")},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/AdminResetPassword", Name: "AdminResetPassword", Kind: RPCKind("unary")},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/Authenticate", Name: "Authenticate", Kind: RPCKind("unary")},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/ChangePassword", Name: "ChangePassword", Kind: RPCKind("unary")},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/ChangeUserStatus", Name: "ChangeUserStatus", Kind: RPCKind("unary")},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/ConfirmMFAEnrollment", Name: "ConfirmMFAEnrollment", Kind: RPCKind("unary")},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/CreateSession", Name: "CreateSession", Kind: RPCKind("unary")},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/CreateUser", Name: "CreateUser", Kind: RPCKind("unary")},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/EnrollMFA", Name: "EnrollMFA", Kind: RPCKind("unary")},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/GetSession", Name: "GetSession", Kind: RPCKind("unary")},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/GetUser", Name: "GetUser", Kind: RPCKind("unary")},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/ListSessions", Name: "ListSessions", Kind: RPCKind("unary")},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/ListUsers", Name: "ListUsers", Kind: RPCKind("unary")},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/Login", Name: "Login", Kind: RPCKind("unary")},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/Logout", Name: "Logout", Kind: RPCKind("unary")},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/RefreshSession", Name: "RefreshSession", Kind: RPCKind("unary")},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/RefreshToken", Name: "RefreshToken", Kind: RPCKind("unary")},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/ResendOTP", Name: "ResendOTP", Kind: RPCKind("unary")},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/RevokeSession", Name: "RevokeSession", Kind: RPCKind("unary")},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/SendOTP", Name: "SendOTP", Kind: RPCKind("unary")},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/UpdateUser", Name: "UpdateUser", Kind: RPCKind("unary")},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/ValidateCSRF", Name: "ValidateCSRF", Kind: RPCKind("unary")},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/ValidateToken", Name: "ValidateToken", Kind: RPCKind("unary")},
	{Service: "AuthnService", ServicePkg: "udb.core.authn.services.v1", FullMethod: "/udb.core.authn.services.v1.AuthnService/VerifyOTP", Name: "VerifyOTP", Kind: RPCKind("unary")},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/AssignRole", Name: "AssignRole", Kind: RPCKind("unary")},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/Authorize", Name: "Authorize", Kind: RPCKind("unary")},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/BatchCheckPermissions", Name: "BatchCheckPermissions", Kind: RPCKind("unary")},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/CheckAccess", Name: "CheckAccess", Kind: RPCKind("unary")},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/CreatePolicyRule", Name: "CreatePolicyRule", Kind: RPCKind("unary")},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/CreateRole", Name: "CreateRole", Kind: RPCKind("unary")},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/DeletePolicyRule", Name: "DeletePolicyRule", Kind: RPCKind("unary")},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/DeleteRole", Name: "DeleteRole", Kind: RPCKind("unary")},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/GetNativeAccess", Name: "GetNativeAccess", Kind: RPCKind("unary")},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/GetPolicyBundle", Name: "GetPolicyBundle", Kind: RPCKind("unary")},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/GetPolicyRule", Name: "GetPolicyRule", Kind: RPCKind("unary")},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/GetRole", Name: "GetRole", Kind: RPCKind("unary")},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/LintAuthzPolicies", Name: "LintAuthzPolicies", Kind: RPCKind("unary")},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/ListAccessDecisionAudits", Name: "ListAccessDecisionAudits", Kind: RPCKind("unary")},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/ListPolicyRules", Name: "ListPolicyRules", Kind: RPCKind("unary")},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/ListRoles", Name: "ListRoles", Kind: RPCKind("unary")},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/ListUserPermissions", Name: "ListUserPermissions", Kind: RPCKind("unary")},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/ListUserRoles", Name: "ListUserRoles", Kind: RPCKind("unary")},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/PutAuthzPolicy", Name: "PutAuthzPolicy", Kind: RPCKind("unary")},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/PutRelationship", Name: "PutRelationship", Kind: RPCKind("unary")},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/PutRoleBinding", Name: "PutRoleBinding", Kind: RPCKind("unary")},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/RevokeRole", Name: "RevokeRole", Kind: RPCKind("unary")},
	{Service: "AuthzService", ServicePkg: "udb.core.authz.services.v1", FullMethod: "/udb.core.authz.services.v1.AuthzService/UpdateRole", Name: "UpdateRole", Kind: RPCKind("unary")},
	{Service: "NotificationService", ServicePkg: "udb.core.notification.services.v1", FullMethod: "/udb.core.notification.services.v1.NotificationService/GetDeliveryStats", Name: "GetDeliveryStats", Kind: RPCKind("unary")},
	{Service: "NotificationService", ServicePkg: "udb.core.notification.services.v1", FullMethod: "/udb.core.notification.services.v1.NotificationService/GetNotification", Name: "GetNotification", Kind: RPCKind("unary")},
	{Service: "NotificationService", ServicePkg: "udb.core.notification.services.v1", FullMethod: "/udb.core.notification.services.v1.NotificationService/GetPreference", Name: "GetPreference", Kind: RPCKind("unary")},
	{Service: "NotificationService", ServicePkg: "udb.core.notification.services.v1", FullMethod: "/udb.core.notification.services.v1.NotificationService/GetTemplate", Name: "GetTemplate", Kind: RPCKind("unary")},
	{Service: "NotificationService", ServicePkg: "udb.core.notification.services.v1", FullMethod: "/udb.core.notification.services.v1.NotificationService/ListNotifications", Name: "ListNotifications", Kind: RPCKind("unary")},
	{Service: "NotificationService", ServicePkg: "udb.core.notification.services.v1", FullMethod: "/udb.core.notification.services.v1.NotificationService/ListPreferences", Name: "ListPreferences", Kind: RPCKind("unary")},
	{Service: "NotificationService", ServicePkg: "udb.core.notification.services.v1", FullMethod: "/udb.core.notification.services.v1.NotificationService/ListTemplates", Name: "ListTemplates", Kind: RPCKind("unary")},
	{Service: "NotificationService", ServicePkg: "udb.core.notification.services.v1", FullMethod: "/udb.core.notification.services.v1.NotificationService/RetryNotification", Name: "RetryNotification", Kind: RPCKind("unary")},
	{Service: "NotificationService", ServicePkg: "udb.core.notification.services.v1", FullMethod: "/udb.core.notification.services.v1.NotificationService/SendNotification", Name: "SendNotification", Kind: RPCKind("unary")},
	{Service: "NotificationService", ServicePkg: "udb.core.notification.services.v1", FullMethod: "/udb.core.notification.services.v1.NotificationService/SetPreference", Name: "SetPreference", Kind: RPCKind("unary")},
	{Service: "NotificationService", ServicePkg: "udb.core.notification.services.v1", FullMethod: "/udb.core.notification.services.v1.NotificationService/UpsertTemplate", Name: "UpsertTemplate", Kind: RPCKind("unary")},
	{Service: "TenantService", ServicePkg: "udb.core.tenant.services.v1", FullMethod: "/udb.core.tenant.services.v1.TenantService/CreateTenant", Name: "CreateTenant", Kind: RPCKind("unary")},
	{Service: "TenantService", ServicePkg: "udb.core.tenant.services.v1", FullMethod: "/udb.core.tenant.services.v1.TenantService/GetTenant", Name: "GetTenant", Kind: RPCKind("unary")},
	{Service: "TenantService", ServicePkg: "udb.core.tenant.services.v1", FullMethod: "/udb.core.tenant.services.v1.TenantService/GetTenantConfig", Name: "GetTenantConfig", Kind: RPCKind("unary")},
	{Service: "TenantService", ServicePkg: "udb.core.tenant.services.v1", FullMethod: "/udb.core.tenant.services.v1.TenantService/ListTenants", Name: "ListTenants", Kind: RPCKind("unary")},
	{Service: "TenantService", ServicePkg: "udb.core.tenant.services.v1", FullMethod: "/udb.core.tenant.services.v1.TenantService/UpdateTenant", Name: "UpdateTenant", Kind: RPCKind("unary")},
	{Service: "TenantService", ServicePkg: "udb.core.tenant.services.v1", FullMethod: "/udb.core.tenant.services.v1.TenantService/UpdateTenantConfig", Name: "UpdateTenantConfig", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/ActivateCatalog", Name: "ActivateCatalog", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/AnalyticalQuery", Name: "AnalyticalQuery", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/ApplyMigration", Name: "ApplyMigration", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/ApproveMigrationPlan", Name: "ApproveMigrationPlan", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/BatchSelect", Name: "BatchSelect", Kind: RPCKind("bidi")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/BatchUpsert", Name: "BatchUpsert", Kind: RPCKind("bidi")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/BeginTx", Name: "BeginTx", Kind: RPCKind("bidi")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/CacheDelete", Name: "CacheDelete", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/CacheGet", Name: "CacheGet", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/CacheScan", Name: "CacheScan", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/CacheSet", Name: "CacheSet", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/CreateMaterializedView", Name: "CreateMaterializedView", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/Delete", Name: "Delete", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/DeletePolicy", Name: "DeletePolicy", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/DismissDlqEvent", Name: "DismissDlqEvent", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/DocumentDelete", Name: "DocumentDelete", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/DocumentFind", Name: "DocumentFind", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/DocumentGet", Name: "DocumentGet", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/DocumentUpsert", Name: "DocumentUpsert", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/DropResource", Name: "DropResource", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/EnqueueOutboxEvent", Name: "EnqueueOutboxEvent", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/EnsureProject", Name: "EnsureProject", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/EnsureResource", Name: "EnsureResource", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/GeneratePresignedUrl", Name: "GeneratePresignedUrl", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/GenericDispatch", Name: "GenericDispatch", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/GetAdminSummary", Name: "GetAdminSummary", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/GetCapabilities", Name: "GetCapabilities", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/GetCatalogManifest", Name: "GetCatalogManifest", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/GetCatalogVersion", Name: "GetCatalogVersion", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/GetCatalogVersions", Name: "GetCatalogVersions", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/GetCdcStatus", Name: "GetCdcStatus", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/GetDlqEvent", Name: "GetDlqEvent", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/GetHealthReport", Name: "GetHealthReport", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/GetMigrationStatus", Name: "GetMigrationStatus", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/GetObject", Name: "GetObject", Kind: RPCKind("server_streaming")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/GetSaga", Name: "GetSaga", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/GraphMutate", Name: "GraphMutate", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/GraphQuery", Name: "GraphQuery", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/InitiateMultipartUpload", Name: "InitiateMultipartUpload", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/LintPolicies", Name: "LintPolicies", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/ListAdminAuditLogs", Name: "ListAdminAuditLogs", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/ListDlqEvents", Name: "ListDlqEvents", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/ListMessageSchemas", Name: "ListMessageSchemas", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/ListMigrationRuns", Name: "ListMigrationRuns", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/ListPolicies", Name: "ListPolicies", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/ListProjects", Name: "ListProjects", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/ListResources", Name: "ListResources", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/ListSagas", Name: "ListSagas", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/LookupMessageSchema", Name: "LookupMessageSchema", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/MarkSagaReviewed", Name: "MarkSagaReviewed", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/PauseCdc", Name: "PauseCdc", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/PlanMigration", Name: "PlanMigration", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/PreviewCdcRedaction", Name: "PreviewCdcRedaction", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/PublishCDC", Name: "PublishCDC", Kind: RPCKind("server_streaming")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/PutObject", Name: "PutObject", Kind: RPCKind("client_streaming")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/PutPolicy", Name: "PutPolicy", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/QuarantineDlqEvent", Name: "QuarantineDlqEvent", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/ReloadPolicies", Name: "ReloadPolicies", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/ReplayDlqEvent", Name: "ReplayDlqEvent", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/ResumeCdc", Name: "ResumeCdc", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/RetrySagaCompensation", Name: "RetrySagaCompensation", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/RollbackCatalog", Name: "RollbackCatalog", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/ScanProjectionDrift", Name: "ScanProjectionDrift", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/Select", Name: "Select", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/SelectV2", Name: "SelectV2", Kind: RPCKind("server_streaming")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/StageCatalog", Name: "StageCatalog", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/StepDownCdcLeader", Name: "StepDownCdcLeader", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/TimeSeriesQuery", Name: "TimeSeriesQuery", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/TimeSeriesWrite", Name: "TimeSeriesWrite", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/Upsert", Name: "Upsert", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/ValidateCatalog", Name: "ValidateCatalog", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/VectorBatchUpsert", Name: "VectorBatchUpsert", Kind: RPCKind("bidi")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/VectorHybridSearch", Name: "VectorHybridSearch", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/VectorSearch", Name: "VectorSearch", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/VectorUpsert", Name: "VectorUpsert", Kind: RPCKind("unary")},
	{Service: "DataBroker", ServicePkg: "udb.services.v1", FullMethod: "/udb.services.v1.DataBroker/VerifyAdminAuditLog", Name: "VerifyAdminAuditLog", Kind: RPCKind("unary")},
}

// ServiceRPCCounts maps each service's full name to its RPC count.
var ServiceRPCCounts = map[string]int{
	"udb.core.analytics.services.v1.AnalyticsService":       7,
	"udb.core.apikey.services.v1.ApiKeyService":             7,
	"udb.core.authn.services.v1.AuthnService":               23,
	"udb.core.authz.services.v1.AuthzService":               23,
	"udb.core.notification.services.v1.NotificationService": 11,
	"udb.core.tenant.services.v1.TenantService":             6,
	"udb.services.v1.DataBroker":                            76,
}

// rpcIndex is a fast Name->RPCInfo lookup built from AllRPCs at init.
var rpcIndex = func() map[string]RPCInfo {
	m := make(map[string]RPCInfo, len(AllRPCs))
	for _, r := range AllRPCs {
		m[r.Name] = r
		m[r.FullMethod] = r
	}
	return m
}()

// LookupRPC finds an RPC by short name (e.g. "Select") or full method path.
func LookupRPC(nameOrPath string) (RPCInfo, bool) {
	r, ok := rpcIndex[nameOrPath]
	return r, ok
}

func init() {
	if GeneratedProtocolVersion != ProtocolVersion {
		// Guard against a stale hand-written ProtocolVersion drifting from the
		// generated wire version. Generation keeps them aligned.
		panic(fmt.Sprintf(
			"udbclient: generated protocol version %q != hand-written ProtocolVersion %q; regenerate the SDK",
			GeneratedProtocolVersion, ProtocolVersion))
	}
}
