// Generated by `udb sdk generate` from the embedded proto descriptor set. Edit the template under sdk-templates/<lang>/, not this file.
//
// UDB CLI launcher (java) — pinned to udb v0.3.2.
//
// "Installing the SDK gives you the udb CLI." This launcher is wired as the
// executable main class via the maven-assembly / appassembler config the
// generator adds to sdk/java/pom.xml. It:
//   1. honours $UDB_BIN if it points at an executable;
//   2. else uses an already-installed `udb` on $PATH IF its `--version` matches
//      v0.3.2 (so the CLI stays version-matched to this SDK);
//   3. else downloads the matching release asset from
//      github.com/fahara02/udb (tag v0.3.2) into a per-user cache dir
//      and execs it.
//
// All trailing args are forwarded verbatim, e.g.:
//   java -jar udb-java-client-cli.jar sdk generate --help
package dev.udb.cli;

import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.nio.file.attribute.PosixFilePermission;
import java.util.Locale;
import java.util.Set;

/** Locates (or downloads) the version-matched udb binary and execs it. */
public final class Launcher {
  /** SDK-pinned udb version; the CLI is fetched/validated against this tag. */
  public static final String UDB_VERSION = "0.3.2";

  private static final String REPO = "fahara02/udb";

  private Launcher() {}

  public static void main(String[] args) throws Exception {
    Path bin = resolveBinary();
    System.exit(exec(bin, args));
  }

  /** Resolve the udb binary path, downloading the pinned release if necessary. */
  public static Path resolveBinary() throws IOException, InterruptedException {
    String override = System.getenv("UDB_BIN");
    if (override != null && !override.isBlank()) {
      Path p = Path.of(override);
      if (Files.isExecutable(p)) {
        return p;
      }
    }

    Path onPath = findOnPath();
    if (onPath != null && versionMatches(onPath)) {
      return onPath;
    }

    Path cached = cachedBinaryPath();
    if (Files.isExecutable(cached)) {
      return cached;
    }
    return download(cached);
  }

  private static boolean isWindows() {
    return System.getProperty("os.name", "").toLowerCase(Locale.ROOT).contains("win");
  }

  private static String exeName() {
    return isWindows() ? "udb.exe" : "udb";
  }

  /** First `udb` found on $PATH, or null. */
  private static Path findOnPath() {
    String path = System.getenv("PATH");
    if (path == null) {
      return null;
    }
    for (String dir : path.split(java.io.File.pathSeparator)) {
      if (dir.isBlank()) {
        continue;
      }
      Path candidate = Path.of(dir, exeName());
      if (Files.isExecutable(candidate)) {
        return candidate;
      }
    }
    return null;
  }

  private static boolean versionMatches(Path bin) {
    try {
      Process p = new ProcessBuilder(bin.toString(), "--version").redirectErrorStream(true).start();
      String out = new String(p.getInputStream().readAllBytes()).trim();
      p.waitFor();
      // `udb --version` prints e.g. "udb 0.3.2"; accept any line containing the tag.
      return out.contains(UDB_VERSION);
    } catch (IOException | InterruptedException e) {
      if (e instanceof InterruptedException) {
        Thread.currentThread().interrupt();
      }
      return false;
    }
  }

  /** Per-user cache path for the pinned binary. */
  private static Path cachedBinaryPath() {
    Path base;
    if (isWindows()) {
      String localAppData = System.getenv("LOCALAPPDATA");
      base = Path.of(localAppData != null ? localAppData : System.getProperty("user.home"));
    } else {
      String xdg = System.getenv("XDG_CACHE_HOME");
      base =
          xdg != null && !xdg.isBlank()
              ? Path.of(xdg)
              : Path.of(System.getProperty("user.home"), ".cache");
    }
    return base.resolve("udb").resolve("v" + UDB_VERSION).resolve(exeName());
  }

  /**
   * The per-OS/arch release asset name. Mirrors the GitHub release naming for
   * github.com/fahara02/udb (e.g. {@code udb-v0.3.2-x86_64-unknown-linux-gnu}).
   */
  static String assetName() {
    String os = System.getProperty("os.name", "").toLowerCase(Locale.ROOT);
    String arch = System.getProperty("os.arch", "").toLowerCase(Locale.ROOT);

    String archTriple;
    if (arch.contains("aarch64") || arch.contains("arm64")) {
      archTriple = "aarch64";
    } else {
      archTriple = "x86_64";
    }

    String target;
    if (os.contains("win")) {
      target = archTriple + "-pc-windows-msvc";
      return "udb-v" + UDB_VERSION + "-" + target + ".exe";
    } else if (os.contains("mac") || os.contains("darwin")) {
      target = archTriple + "-apple-darwin";
    } else {
      target = archTriple + "-unknown-linux-gnu";
    }
    return "udb-v" + UDB_VERSION + "-" + target;
  }

  private static Path download(Path dest) throws IOException, InterruptedException {
    String url =
        "https://github.com/" + REPO + "/releases/download/v" + UDB_VERSION + "/" + assetName();
    Files.createDirectories(dest.getParent());

    HttpClient http =
        HttpClient.newBuilder().followRedirects(HttpClient.Redirect.NORMAL).build();
    HttpRequest req = HttpRequest.newBuilder(URI.create(url)).GET().build();
    HttpResponse<InputStream> resp = http.send(req, HttpResponse.BodyHandlers.ofInputStream());
    if (resp.statusCode() != 200) {
      throw new IOException(
          "udb: failed to download CLI from " + url + " (HTTP " + resp.statusCode() + ")");
    }

    Path tmp = Files.createTempFile(dest.getParent(), "udb-", ".part");
    try (InputStream in = resp.body()) {
      Files.copy(in, tmp, StandardCopyOption.REPLACE_EXISTING);
    }
    if (!isWindows()) {
      Set<PosixFilePermission> perms =
          Set.of(
              PosixFilePermission.OWNER_READ,
              PosixFilePermission.OWNER_WRITE,
              PosixFilePermission.OWNER_EXECUTE,
              PosixFilePermission.GROUP_READ,
              PosixFilePermission.GROUP_EXECUTE,
              PosixFilePermission.OTHERS_READ,
              PosixFilePermission.OTHERS_EXECUTE);
      try {
        Files.setPosixFilePermissions(tmp, perms);
      } catch (UnsupportedOperationException ignored) {
        // Non-POSIX filesystem; nothing to do.
      }
    }
    Files.move(tmp, dest, StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.ATOMIC_MOVE);
    return dest;
  }

  private static int exec(Path bin, String[] args) throws IOException, InterruptedException {
    String[] cmd = new String[args.length + 1];
    cmd[0] = bin.toString();
    System.arraycopy(args, 0, cmd, 1, args.length);
    Process p = new ProcessBuilder(cmd).inheritIO().start();
    return p.waitFor();
  }
}
