//! `udb env` — generate a working `.env` instead of assembling one by hand.
//!
//! `.env.example` documents ~270 variables. That is the right reference and the
//! wrong starting point: an operator bringing up a broker has to read all of it
//! to discover the ten or so that actually decide whether the process boots, and
//! then invent values for the secrets. This emits a file that starts a broker as
//! written, with real generated secrets and one line of rationale per variable,
//! and points at `.env.example` for everything else.
//!
//! The values here are the same defaults the runtime resolves, so a generated
//! file and an empty environment behave identically — the file exists to make
//! the decisions visible and editable, not to change them.

use std::fmt::Write as _;
use std::path::Path;

/// Deployment posture the generated file targets.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum EnvProfile {
    /// Loopback, no client certificates, seeded admin — for a laptop.
    Dev,
    /// Mandatory mTLS and the full identity surface — the posture `UDB_ENV=production`
    /// enforces anyway, written out so it is reviewable before it is enforced.
    Enterprise,
}

impl EnvProfile {
    pub(crate) fn parse(raw: &str) -> Option<Self> {
        match raw.trim().to_ascii_lowercase().as_str() {
            "dev" | "development" | "local" => Some(Self::Dev),
            "enterprise" | "prod" | "production" => Some(Self::Enterprise),
            _ => None,
        }
    }

    fn label(self) -> &'static str {
        match self {
            Self::Dev => "dev",
            Self::Enterprise => "enterprise",
        }
    }
}

/// A 32-byte URL-safe secret. Uses the OS CSPRNG — a generated file must never
/// ship a shared literal, because a placeholder that boots is a placeholder that
/// reaches production.
fn generated_secret() -> String {
    const ALPHABET: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    let mut raw = [0u8; 48];
    getrandom::getrandom(&mut raw).expect("OS CSPRNG unavailable");
    raw.iter()
        .map(|byte| ALPHABET[*byte as usize % ALPHABET.len()] as char)
        .collect()
}

fn section(out: &mut String, title: &str, why: &str) {
    let _ = write!(
        out,
        "\n# ─────────────────────────────────────────────────────────────────────────\n\
         # {title}\n\
         # {why}\n\
         # ─────────────────────────────────────────────────────────────────────────\n"
    );
}

fn var(out: &mut String, key: &str, value: &str, why: &str) {
    let _ = write!(out, "# {why}\n{key}={value}\n");
}

fn commented(out: &mut String, key: &str, value: &str, why: &str) {
    let _ = write!(out, "# {why}\n# {key}={value}\n");
}

/// Render the file. Pure — no I/O, so the shape is unit-testable.
pub(crate) fn render(profile: EnvProfile, dsn: &str) -> String {
    let mut out = String::new();
    let _ = write!(
        &mut out,
        "# UDB environment — generated by `udb env --profile {}`\n\
         #\n\
         # This starts a broker as written. Every value is the default the runtime\n\
         # would resolve anyway; they are spelled out so the decisions are visible.\n\
         # `.env.example` documents the full surface (~270 variables) — reach for it\n\
         # when you need something that is not here.\n\
         #\n\
         # Verify before first boot:\n\
         #   udb requirements     # backends this manifest needs, and whether they are set\n\
         #   udb doctor           # configuration and connectivity\n\
         #   udb verify --live --dsn \"$UDB_PG_DSN\"   # live schema vs manifest, read-only\n",
        profile.label()
    );

    section(
        &mut out,
        "Identity",
        "UDB_ENV=production force-enables the mandatory-mTLS flags below.",
    );
    var(
        &mut out,
        "UDB_ENV",
        match profile {
            EnvProfile::Dev => "development",
            EnvProfile::Enterprise => "production",
        },
        "Deployment posture. `production` refuses to start without the TLS material below.",
    );
    var(
        &mut out,
        "UDB_APP_NAME",
        "udb",
        "Identifies this broker in logs, metrics and audit records.",
    );

    section(
        &mut out,
        "Postgres — the one mandatory backend",
        "Everything else is optional; without this the broker cannot start.",
    );
    var(
        &mut out,
        "UDB_PG_DSN",
        dsn,
        "Direct/session endpoint. A transaction pooler breaks advisory locks and LISTEN/NOTIFY.",
    );
    var(
        &mut out,
        "UDB_PG_MAX_CONNECTIONS",
        "20",
        "Upper bound of the broker's pool. Keep below the server's max_connections.",
    );

    section(
        &mut out,
        "Listeners",
        "Three separate surfaces with three different credential types — do not merge them.",
    );
    var(
        &mut out,
        "UDB_GRPC_ADDR",
        "0.0.0.0:50051",
        "Data plane. Casbin-authorized; the surface applications talk to.",
    );
    var(
        &mut out,
        "UDB_METRICS_ADDR",
        "0.0.0.0:9090",
        "Prometheus scrape endpoint. Expose to your monitoring network only.",
    );

    section(
        &mut out,
        "Secrets — generated per file, never shared",
        "Rotate with your normal secret process; these are real values, not placeholders.",
    );
    var(
        &mut out,
        "UDB_ENCRYPTION_KEY",
        &generated_secret(),
        "At-rest encryption for secret columns and vault material. Losing it loses the data.",
    );
    var(
        &mut out,
        "UDB_APPROVAL_SIGNING_KEY",
        &generated_secret(),
        "Signs migration approval plans so a plan cannot be edited between review and apply.",
    );

    section(
        &mut out,
        "Transport security",
        "Mandatory in production. Generate real material; self-signed is fine for a rehearsal.",
    );
    match profile {
        EnvProfile::Enterprise => {
            var(
                &mut out,
                "UDB_MTLS_REQUIRED",
                "true",
                "Reject any client without a certificate signed by the CA below.",
            );
            var(
                &mut out,
                "UDB_MTLS_CLIENT_CA_PATH",
                "/etc/udb/tls/client-ca.pem",
                "CA bundle that client certificates are verified against.",
            );
            var(
                &mut out,
                "UDB_JWT_PUBLIC_KEY",
                "/etc/udb/tls/jwt-public.pem",
                "RS256 public key used to verify bearer tokens.",
            );
        }
        EnvProfile::Dev => {
            commented(
                &mut out,
                "UDB_MTLS_REQUIRED",
                "true",
                "Off for local work. `UDB_ENV=production` turns this on regardless.",
            );
            commented(
                &mut out,
                "UDB_MTLS_CLIENT_CA_PATH",
                "/etc/udb/tls/client-ca.pem",
                "CA bundle for client certificates, once mTLS is on.",
            );
        }
    }

    section(
        &mut out,
        "Migration and upgrade",
        "These decide what happens to a database that already has data in it.",
    );
    var(
        &mut out,
        "UDB_MIGRATE_ENABLED",
        match profile {
            EnvProfile::Dev => "true",
            EnvProfile::Enterprise => "false",
        },
        match profile {
            EnvProfile::Dev => "Apply schema changes on startup. Convenient locally.",
            EnvProfile::Enterprise => {
                "Off on purpose: run `udb plan` and apply deliberately, not on a restart."
            }
        },
    );
    var(
        &mut out,
        "UDB_DDL_CONCURRENCY",
        "1",
        "Serialise DDL. Higher values contend on locks against a live database.",
    );
    commented(
        &mut out,
        "UDB_MIGRATION_EMERGENCY_AUTO_ALTER",
        "true",
        "Repair path: lets startup feed live-vs-manifest drift to the repair planner \
         instead of fail-closing. Turn on only when a verified drift is blocking a boot.",
    );

    let _ = write!(
        &mut out,
        "\n# Next: `udb requirements` lists any backend this manifest needs beyond Postgres\n\
         # (object storage, vector, cache, streaming) with the exact variable for each.\n"
    );
    out
}

/// Write the rendered file, refusing to clobber without `--force`.
pub(crate) fn run(profile: EnvProfile, out_path: Option<&str>, force: bool, dsn: &str) -> i32 {
    let rendered = render(profile, dsn);
    let Some(path) = out_path else {
        print!("{rendered}");
        return 0;
    };
    let target = Path::new(path);
    if target.exists() && !force {
        eprintln!(
            "udb env: {} already exists — refusing to overwrite.\n\
             An env file holds generated secrets; replacing one silently can lock you out of\n\
             encrypted data. Re-run with --force if that is what you want.",
            target.display()
        );
        return 1;
    }
    match std::fs::write(target, &rendered) {
        Ok(()) => {
            eprintln!(
                "udb env: wrote {} ({} profile).\n\
                 Secrets in this file are freshly generated — keep it out of version control.\n\
                 Next: udb requirements && udb doctor",
                target.display(),
                profile.label()
            );
            0
        }
        Err(err) => {
            eprintln!("udb env: cannot write {}: {err}", target.display());
            1
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn profiles_parse_the_names_operators_actually_type() {
        assert_eq!(EnvProfile::parse("dev"), Some(EnvProfile::Dev));
        assert_eq!(EnvProfile::parse("local"), Some(EnvProfile::Dev));
        assert_eq!(
            EnvProfile::parse("ENTERPRISE"),
            Some(EnvProfile::Enterprise)
        );
        assert_eq!(
            EnvProfile::parse("production"),
            Some(EnvProfile::Enterprise)
        );
        assert_eq!(EnvProfile::parse("nonsense"), None);
    }

    #[test]
    fn generated_secrets_are_unique_and_long() {
        let a = generated_secret();
        let b = generated_secret();
        assert_ne!(a, b, "each generated file must get its own secret");
        assert!(a.len() >= 32, "secret must not be trivially guessable");
        assert!(
            a.chars().all(|c| c.is_ascii_alphanumeric()),
            "secret must be safe to paste into a .env without quoting: {a}"
        );
    }

    #[test]
    fn enterprise_profile_is_production_posture() {
        let rendered = render(EnvProfile::Enterprise, "postgres://localhost/udb");
        assert!(rendered.contains("UDB_ENV=production"));
        assert!(
            rendered.contains("UDB_MTLS_REQUIRED=true"),
            "enterprise must enable mTLS, not merely mention it"
        );
        assert!(
            rendered.contains("UDB_MIGRATE_ENABLED=false"),
            "a production broker must not migrate on restart"
        );
    }

    #[test]
    fn dev_profile_boots_without_certificate_material() {
        let rendered = render(EnvProfile::Dev, "postgres://localhost/udb");
        assert!(rendered.contains("UDB_ENV=development"));
        assert!(
            rendered.contains("# UDB_MTLS_REQUIRED=true"),
            "dev must leave mTLS commented, not enabled"
        );
        assert!(rendered.contains("UDB_MIGRATE_ENABLED=true"));
    }

    #[test]
    fn the_dsn_reaches_the_file_and_the_repair_knob_is_documented_but_off() {
        let rendered = render(EnvProfile::Enterprise, "postgres://u:p@db:5432/app");
        assert!(rendered.contains("UDB_PG_DSN=postgres://u:p@db:5432/app"));
        // The repair path must be discoverable but never on by default.
        assert!(rendered.contains("# UDB_MIGRATION_EMERGENCY_AUTO_ALTER=true"));
        assert!(!rendered.contains("\nUDB_MIGRATION_EMERGENCY_AUTO_ALTER=true"));
    }
}
