#!/usr/bin/env bash
# One-time enterprise bootstrap for the UDB TypeScript enterprise example.
#
# Produces, under ./secrets/:
#   - jwt-private.pem / jwt-public.pem   RS256 signing keys the broker issues JWTs with
#   - enterprise.env                     every secret/value `serve.sh` + the client need
#
# and mints the first admin user OFFLINE (straight to Postgres — no running
# broker, no pre-existing credential), binding it to `organization_owner`
# (→ udb:* scopes on login). It then writes a real ABAC policy granting that
# tenant data access, because the broker's live authorization is DEFAULT-DENY:
# without a seeded ABAC policy every data RPC is PERMISSION_DENIED even for the
# org owner. THIS is the real enterprise-authz friction, made explicit.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
SECRETS="$ROOT/secrets"
mkdir -p "$SECRETS"

# Resolve the UDB CLI.
if [[ -n "${UDB_CLI:-}" && -x "${UDB_CLI}" ]]; then CLI="$UDB_CLI"
elif command -v udb >/dev/null 2>&1; then CLI="$(command -v udb)"
elif [[ -x "$REPO_ROOT/target/release/udb.exe" ]]; then CLI="$REPO_ROOT/target/release/udb.exe"
elif [[ -x "$REPO_ROOT/target/debug/udb.exe" ]]; then CLI="$REPO_ROOT/target/debug/udb.exe"
elif [[ -x "$REPO_ROOT/target/release/udb" ]]; then CLI="$REPO_ROOT/target/release/udb"
else echo "Could not find the UDB CLI (set UDB_CLI, or 'cargo build --bin udb')." >&2; exit 1; fi

PG_PORT="${UDB_POSTGRES_PORT:-55432}"
PG_DSN="${UDB_PG_DSN:-postgres://udb:udb@localhost:${PG_PORT}/udb_enterprise?sslmode=disable}"
ADMIN_USER="${UDB_USER:-admin}"
ADMIN_PASS="${UDB_PASS:-AdminPassw0rd!23}"
TENANT_CODE="${UDB_TENANT:-acme}"

# RS256 keypair (reused on re-run so the same tokens keep verifying).
if [[ ! -f "$SECRETS/jwt-private.pem" ]]; then
  openssl genrsa -out "$SECRETS/jwt-private.pem" 2048 2>/dev/null
  openssl rsa -in "$SECRETS/jwt-private.pem" -pubout -out "$SECRETS/jwt-public.pem" 2>/dev/null
  echo "generated RS256 JWT keypair"
fi

# Keyed-HMAC secrets (reused on re-run; bootstrap + serve MUST agree on the
# password-hash secret or login can never verify the stored hash).
if [[ ! -f "$SECRETS/hmac.env" ]]; then
  {
    echo "UDB_PASSWORD_HASH_SECRET=$(openssl rand -hex 32)"
    echo "UDB_SESSION_HASH_SECRET=$(openssl rand -hex 32)"
  } > "$SECRETS/hmac.env"
fi
# shellcheck disable=SC1091
source "$SECRETS/hmac.env"

# Mint the admin OFFLINE (needs only the DSN + password-hash secret).
echo "bootstrapping admin user '$ADMIN_USER' (tenant code '$TENANT_CODE')..."
BOOT_OUT="$(UDB_PG_DSN="$PG_DSN" UDB_PASSWORD_HASH_SECRET="$UDB_PASSWORD_HASH_SECRET" \
  "$CLI" auth bootstrap user \
    --username "$ADMIN_USER" --email "${ADMIN_USER}@acme.example" \
    --password "$ADMIN_PASS" --tenant "$TENANT_CODE" --project default 2>&1)"
echo "$BOOT_OUT"
TENANT_ID="$(printf '%s' "$BOOT_OUT" | grep -oE '"tenant_id"[[:space:]]*:[[:space:]]*"[^"]+"' | head -1 | sed -E 's/.*"tenant_id"[[:space:]]*:[[:space:]]*"([^"]+)".*/\1/')"
if [[ -z "$TENANT_ID" ]]; then echo "FAILED: could not parse canonical tenant_id from bootstrap output" >&2; exit 1; fi
echo "canonical tenant UUID: $TENANT_ID"

# Real ABAC policy: allow this tenant's principals to do data ops (default-deny
# otherwise). required_scope reflects read vs write; the org owner holds udb:*,
# which satisfies both. Loaded live via UDB_ABAC_POLICIES_JSON at serve time.
# Compact (no spaces/newlines) so it survives `source`-ing the env file.
ABAC_JSON='[{"effect":"allow","service_identity":"*","tenant_id":"'"$TENANT_ID"'","purpose":"*","message_type":"*","operation":"data.select","required_scope":"udb:read"},{"effect":"allow","service_identity":"*","tenant_id":"'"$TENANT_ID"'","purpose":"*","message_type":"*","operation":"data.upsert","required_scope":"udb:write"},{"effect":"allow","service_identity":"*","tenant_id":"'"$TENANT_ID"'","purpose":"*","message_type":"*","operation":"data.delete","required_scope":"udb:write"}]'

# Emit the env file serve.sh + the client read. Values that contain shell-special
# characters (the ABAC JSON) are SINGLE-QUOTED so `source` treats them literally.
{
  echo "# Generated by bootstrap.sh — do not commit (contains secrets)."
  echo "UDB_PG_DSN='$PG_DSN'"
  echo "UDB_PASSWORD_HASH_SECRET='$UDB_PASSWORD_HASH_SECRET'"
  echo "UDB_SESSION_HASH_SECRET='$UDB_SESSION_HASH_SECRET'"
  echo "UDB_JWT_PRIVATE_KEY='$SECRETS/jwt-private.pem'"
  echo "UDB_JWT_PUBLIC_KEY='$SECRETS/jwt-public.pem'"
  echo "UDB_TENANT_ID='$TENANT_ID'"
  echo "UDB_TENANT='$TENANT_CODE'"
  echo "UDB_USER='$ADMIN_USER'"
  echo "UDB_PASS='$ADMIN_PASS'"
  echo "UDB_ABAC_POLICIES_JSON='$ABAC_JSON'"
} > "$SECRETS/enterprise.env"

echo
echo "wrote $SECRETS/enterprise.env"
echo "next: ./scripts/serve.sh   (starts the enterprise broker)"
