#!/usr/bin/env python3
"""Source guard for Chapter 12 docs/CI freshness posture.

This is intentionally source-only. It does not regenerate native docs, run
cargo, or rewrite generated artifacts; CI owns the expensive regenerate-and-diff
checks. The guard pins the committed shape that Chapter 12 depends on so future
edits cannot silently drop the docs drift gate, client-layer docs, or
No-Internal-Tables rule.
"""

from __future__ import annotations

import argparse
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

REQUIRED_FILES = {
    "docs/generated/native-services.md": (
        ("Generated by `udb native docs`", "generated native docs provenance"),
        ("Contract version `7.0.0` · 27 native services.", "native docs contract/version header"),
        ("| Service | Display name | Category | Default | Dependencies | RPCs | Listeners |", "native docs service table"),
    ),
    "docs/native-services.md": (
        ("## Client layers", "thin-vs-workflow client layers section"),
        ("workflow helper", "first-page workflow helper guidance"),
        ("file upload", "storage workflow helper guidance"),
        ("UploadFile", "Go storage workflow helper snippet"),
        ("sdk/typescript/project.ts", "TypeScript workflow facade link"),
        ("sdk/php/src/UdbProject.php", "PHP workflow facade link"),
        ("GenericDispatch", "raw generated-client escape-hatch discussion"),
        ("Do **not** point `GenericDispatch` at the broker's internal `udb_*` schemas", "no-internal-tables prose rule"),
        ("scripts/check-no-internal-tables.py", "no-internal-tables lint reference"),
    ),
    ".github/workflows/ci.yml": (
        ("Docs/CI freshness posture guard", "docs/CI posture quick-gate step"),
        ("python3 scripts/check-docs-ci-freshness-posture.py --selftest", "docs/CI posture selftest"),
        ("python3 scripts/check-docs-ci-freshness-posture.py", "docs/CI posture repo scan"),
        ("Native docs markdown drift", "native markdown drift step"),
        ("target/debug/udb native docs > docs/generated/native-services.md", "native docs regenerate command"),
        ("git diff --quiet -- docs/generated/native-services.md", "native docs diff gate"),
        ("target/debug/udb native contract-baseline", "native baseline repair command"),
        ("docs/generated/contract-baseline.bin", "native baseline repair target"),
        ("No internal tables guard (masterplan §12)", "no-internal-tables CI step"),
        ("python3 scripts/check-no-internal-tables.py --selftest", "no-internal-tables selftest"),
        ("python3 scripts/check-no-internal-tables.py", "no-internal-tables repo scan"),
        ("docs-links:", "docs-links CI job"),
        ("node --check scripts/check-markdown-links.mjs", "markdown link syntax check"),
        ("node scripts/check-markdown-links.mjs --selftest", "markdown link selftest"),
        ("node scripts/check-markdown-links.mjs", "markdown link repo scan"),
        ("node --check scripts/check-enterprise-readiness.mjs", "enterprise readiness syntax check"),
        ("node scripts/check-enterprise-readiness.mjs --selftest", "enterprise readiness selftest"),
        ("node scripts/check-enterprise-readiness.mjs", "enterprise readiness repo scan"),
    ),
    "scripts/check-no-internal-tables.py": (
        ("DISPATCH_RE = re.compile(r\"GenericDispatch\")", "GenericDispatch matcher"),
        ("INTERNAL_SCHEMA_RE = re.compile", "internal schema matcher"),
        ("EXCLUDE_DIR_PARTS", "generated/test path exclusions"),
        ("RAW_BINDING_NAMES", "raw generated-client binding allowlist"),
        ("WINDOW = 6", "co-location window"),
        ("--selftest", "selftest CLI"),
        ("runs GenericDispatch against an internal udb_* control-plane schema", "failure reason"),
        ("Fix: do not repair/seed native state with raw GenericDispatch SQL", "served-RPC remediation"),
    ),
    "sdk/go/udbclient/live_perf_seed_test.go": (
        ("GenericDispatch INSERT into", "retired raw-dispatch seed regression note"),
        ("UDB_NOTIFICATION_TEST_MODE", "served notification test-mode seed marker"),
        ("__perf_force_failed__", "served notification FAILED-log seed marker"),
        ("without touching internal notification tables", "no internal notification table seed marker"),
        ("register_login_device", "served-path device seed replacement note"),
    ),
}


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="ignore")


def check(root: Path = ROOT) -> list[str]:
    failures: list[str] = []
    for rel, requirements in REQUIRED_FILES.items():
        path = root / rel
        if not path.is_file():
            failures.append(f"{rel}: file is missing")
            continue
        text = read_text(path)
        for needle, label in requirements:
            if needle not in text:
                failures.append(f"{rel}: missing {label}: {needle}")
    return failures


def write_fixture(root: Path, rel: str, text: str) -> None:
    path = root / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def fixture_text(requirements: tuple[tuple[str, str], ...]) -> str:
    return "\n".join(needle for needle, _label in requirements) + "\n"


def run_selftest() -> int:
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        for rel, requirements in REQUIRED_FILES.items():
            write_fixture(root, rel, fixture_text(requirements))

        failures = check(root)
        if failures:
            raise AssertionError(f"good fixture failed: {failures}")

        native_docs = root / "docs" / "generated" / "native-services.md"
        native_docs.write_text(
            read_text(native_docs).replace("Contract version `7.0.0`", "Contract version `6.0.0`"),
            encoding="utf-8",
        )
        failures = check(root)
        if not any("native docs contract/version header" in failure for failure in failures):
            raise AssertionError(f"missing stale native-docs detection: {failures}")

        native_docs.write_text(fixture_text(REQUIRED_FILES["docs/generated/native-services.md"]), encoding="utf-8")
        ci = root / ".github" / "workflows" / "ci.yml"
        ci.write_text(
            read_text(ci).replace(
                "python3 scripts/check-no-internal-tables.py --selftest",
                "python3 scripts/check-no-internal-tables.py --help",
            ),
            encoding="utf-8",
        )
        failures = check(root)
        if not any("no-internal-tables selftest" in failure for failure in failures):
            raise AssertionError(f"missing no-internal-tables CI selftest detection: {failures}")

        ci.write_text(fixture_text(REQUIRED_FILES[".github/workflows/ci.yml"]), encoding="utf-8")
        docs = root / "docs" / "native-services.md"
        docs.write_text(read_text(docs).replace("## Client layers", "## SDK layers"), encoding="utf-8")
        failures = check(root)
        if not any("thin-vs-workflow client layers section" in failure for failure in failures):
            raise AssertionError(f"missing client-layer doc detection: {failures}")

    print("docs/CI freshness posture selftest passed")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--selftest", action="store_true", help="run no-repo fixture assertions")
    args = parser.parse_args()
    if args.selftest:
        return run_selftest()

    failures = check()
    if failures:
        for failure in failures:
            print(f"::error::{failure}")
        return 1
    print("docs/CI freshness posture guard passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
