// <auto-generated>
// Generated by `udb sdk generate` from the embedded proto descriptor set. Edit the template under sdk-templates/<lang>/, not this file.
//
// UDB CLI launcher (version 0.4.27).
//
// Rendered by `udb sdk generate` from
//   sdk-templates/csharp/Udb.Cli/UdbCli.cs.tmpl
// into
//   sdk/csharp/Udb.Cli/UdbCli.cs
//
// Packaged as a .NET global/local tool (see Udb.Cli.csproj <ToolCommandName>udb</ToolCommandName>):
//
//   dotnet tool install --global Udb.Cli --version 0.4.27
//   udb --help
//
// On launch it resolves the version-matched `udb` binary in this order:
//   1. an already-installed `udb` on PATH whose `--version` matches 0.4.27;
//   2. a previously cached download under the per-user cache dir;
//   3. otherwise downloads the v0.4.27 release asset for this OS/arch
//      from https://github.com/fahara02/udb/releases and caches it.
// All arguments are forwarded verbatim and the child's exit code is propagated.
// </auto-generated>
using System.Diagnostics;
using System.Net.Http;
using System.Runtime.InteropServices;
using System.Security.Cryptography;

namespace Udb.Cli;

internal static class UdbCli
{
    private const string Version = "0.4.27";
    private const string Repo = "fahara02/udb";

    private static async Task<int> Main(string[] args)
    {
        try
        {
            var binary = await ResolveBinaryAsync().ConfigureAwait(false);
            return Exec(binary, args);
        }
        catch (Exception ex)
        {
            await Console.Error.WriteLineAsync($"udb-launcher: {ex.Message}").ConfigureAwait(false);
            return 1;
        }
    }

    /// <summary>Find a usable `udb` binary, downloading the matched release if needed.</summary>
    private static async Task<string> ResolveBinaryAsync()
    {
        // 1) PATH, if its version matches.
        var onPath = FindOnPath();
        if (onPath is not null && VersionMatches(onPath))
        {
            return onPath;
        }

        // 2) per-user cache.
        var cached = CachedBinaryPath();
        if (File.Exists(cached))
        {
            return cached;
        }

        // 3) download the matching release asset.
        return await DownloadAsync(cached).ConfigureAwait(false);
    }

    private static string ExeName => RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ? "udb.exe" : "udb";

    private static string? FindOnPath()
    {
        var path = Environment.GetEnvironmentVariable("PATH") ?? string.Empty;
        var sep = RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ? ';' : ':';
        foreach (var dir in path.Split(sep, StringSplitOptions.RemoveEmptyEntries))
        {
            var candidate = Path.Combine(dir.Trim(), ExeName);
            if (File.Exists(candidate))
            {
                return candidate;
            }
        }
        return null;
    }

    private static bool VersionMatches(string binary)
    {
        try
        {
            var psi = new ProcessStartInfo(binary, "--version")
            {
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
            };
            using var proc = Process.Start(psi);
            if (proc is null) return false;
            var stdout = proc.StandardOutput.ReadToEnd();
            proc.WaitForExit(5000);
            return stdout.Contains(Version, StringComparison.Ordinal);
        }
        catch
        {
            return false;
        }
    }

    private static string CacheDir()
    {
        // ~/.cache/udb/<version> on Unix, %LOCALAPPDATA%\udb\<version> on Windows.
        string baseDir;
        if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
        {
            baseDir = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
        }
        else
        {
            var xdg = Environment.GetEnvironmentVariable("XDG_CACHE_HOME");
            baseDir = !string.IsNullOrEmpty(xdg)
                ? xdg
                : Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), ".cache");
        }
        var dir = Path.Combine(baseDir, "udb", Version);
        Directory.CreateDirectory(dir);
        return dir;
    }

    private static string CachedBinaryPath() => Path.Combine(CacheDir(), ExeName);

    /// <summary>
    /// Map the current OS/arch to the published release asset name.
    /// Canonical scheme (see .github/workflows/release-binaries.yml):
    ///   udb-&lt;os&gt;-&lt;arch&gt;[-&lt;variant&gt;]&lt;ext&gt;
    ///   os   = linux | darwin | windows
    ///   arch = amd64 | arm64
    ///   variant = UDB_BIN_VARIANT (omitted when unset/empty/"portable")
    ///   ext  = ".exe" on Windows, otherwise empty
    /// e.g. udb-linux-amd64, udb-windows-amd64.exe, udb-darwin-arm64, udb-linux-amd64-full
    /// </summary>
    private static string AssetName()
    {
        string os =
            RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ? "windows" :
            RuntimeInformation.IsOSPlatform(OSPlatform.OSX) ? "darwin" :
            "linux";
        string arch = RuntimeInformation.OSArchitecture switch
        {
            Architecture.X64 => "amd64",
            Architecture.Arm64 => "arm64",
            var other => other.ToString().ToLowerInvariant(),
        };
        string variant = string.Empty;
        var variantEnv = Environment.GetEnvironmentVariable("UDB_BIN_VARIANT");
        if (!string.IsNullOrEmpty(variantEnv) &&
            !string.Equals(variantEnv, "portable", StringComparison.Ordinal))
        {
            variant = "-" + variantEnv;
        }
        string ext = RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ? ".exe" : string.Empty;
        return $"udb-{os}-{arch}{variant}{ext}";
    }

    /// <summary>
    /// Download the RAW release executable to <paramref name="destination"/>.
    /// The published asset is a raw binary (NOT an archive), so the response
    /// bytes are written straight to disk. On non-Windows the file is marked
    /// executable (0755). The `&lt;asset&gt;.sha256` sidecar is verified best-effort.
    /// </summary>
    private static async Task<string> DownloadAsync(string destination)
    {
        var asset = AssetName();
        var baseUrl = $"https://github.com/{Repo}/releases/download/v{Version}";
        var url = $"{baseUrl}/{asset}";
        await Console.Error.WriteLineAsync($"udb-launcher: downloading {url}").ConfigureAwait(false);

        using var http = new HttpClient();
        http.DefaultRequestHeaders.UserAgent.ParseAdd($"udb-csharp-launcher/{Version}");
        using var resp = await http.GetAsync(url, HttpCompletionOption.ResponseHeadersRead).ConfigureAwait(false);
        resp.EnsureSuccessStatusCode();

        // The asset is a raw executable: stream the response bytes directly to a
        // temp file (no zip/tar extraction).
        var tmp = destination + ".partial";
        await using (var fs = File.Create(tmp))
        {
            await resp.Content.CopyToAsync(fs).ConfigureAwait(false);
        }

        // Best-effort integrity check against the `<asset>.sha256` sidecar.
        await VerifyChecksumAsync(http, $"{url}.sha256", tmp, asset).ConfigureAwait(false);

        if (!RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
        {
            // Mark the raw binary executable (rwxr-xr-x / 0755).
            File.SetUnixFileMode(
                tmp,
                UnixFileMode.UserRead | UnixFileMode.UserWrite | UnixFileMode.UserExecute |
                UnixFileMode.GroupRead | UnixFileMode.GroupExecute |
                UnixFileMode.OtherRead | UnixFileMode.OtherExecute);
        }

        File.Move(tmp, destination, overwrite: true);
        return destination;
    }

    /// <summary>
    /// Verify the downloaded file against its `<paramref name="asset"/>.sha256`
    /// sidecar (sha256sum format: "&lt;hex&gt;  &lt;filename&gt;"). Best-effort: a missing
    /// sidecar is non-fatal; a present-but-mismatching one throws.
    /// </summary>
    private static async Task VerifyChecksumAsync(HttpClient http, string sumUrl, string filePath, string asset)
    {
        string? expected;
        try
        {
            using var resp = await http.GetAsync(sumUrl).ConfigureAwait(false);
            if (!resp.IsSuccessStatusCode)
            {
                return; // sidecar absent -> skip (non-fatal)
            }
            var body = await resp.Content.ReadAsStringAsync().ConfigureAwait(false);
            // First whitespace-delimited token is the hex digest.
            expected = body.Split(new[] { ' ', '\t', '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries)
                           .FirstOrDefault();
        }
        catch
        {
            return; // network/parse failure on the sidecar -> skip (non-fatal)
        }

        if (string.IsNullOrEmpty(expected))
        {
            return;
        }

        string actual;
        await using (var fs = File.OpenRead(filePath))
        {
            var hash = await SHA256.HashDataAsync(fs).ConfigureAwait(false);
            actual = Convert.ToHexString(hash).ToLowerInvariant();
        }

        if (!string.Equals(actual, expected.Trim().ToLowerInvariant(), StringComparison.Ordinal))
        {
            throw new InvalidOperationException(
                $"checksum mismatch for {asset}: expected {expected.Trim()}, got {actual}");
        }
    }

    /// <summary>Exec the resolved binary, forwarding args and the exit code.</summary>
    private static int Exec(string binary, string[] args)
    {
        var psi = new ProcessStartInfo(binary) { UseShellExecute = false };
        foreach (var a in args)
        {
            psi.ArgumentList.Add(a);
        }
        using var proc = Process.Start(psi)
            ?? throw new InvalidOperationException($"failed to start {binary}");
        proc.WaitForExit();
        return proc.ExitCode;
    }
}
