// <auto-generated>
// Generated by `udb sdk generate` from the embedded proto descriptor set. Edit the template under sdk-templates/<lang>/, not this file.
//
// UDB CLI launcher (version 0.3.1).
//
// Rendered by `udb sdk generate` from
//   sdk-templates/csharp/Udb.Cli/UdbCli.cs.tmpl
// into
//   sdk/csharp/Udb.Cli/UdbCli.cs
//
// Packaged as a .NET global/local tool (see Udb.Cli.csproj <ToolCommandName>udb</ToolCommandName>):
//
//   dotnet tool install --global Udb.Cli --version 0.3.1
//   udb --help
//
// On launch it resolves the version-matched `udb` binary in this order:
//   1. an already-installed `udb` on PATH whose `--version` matches 0.3.1;
//   2. a previously cached download under the per-user cache dir;
//   3. otherwise downloads the v0.3.1 release asset for this OS/arch
//      from https://github.com/fahara02/udb/releases and caches it.
// All arguments are forwarded verbatim and the child's exit code is propagated.
// </auto-generated>
using System.Diagnostics;
using System.Net.Http;
using System.Runtime.InteropServices;

namespace Udb.Cli;

internal static class UdbCli
{
    private const string Version = "0.3.1";
    private const string Repo = "fahara02/udb";

    private static async Task<int> Main(string[] args)
    {
        try
        {
            var binary = await ResolveBinaryAsync().ConfigureAwait(false);
            return Exec(binary, args);
        }
        catch (Exception ex)
        {
            await Console.Error.WriteLineAsync($"udb-launcher: {ex.Message}").ConfigureAwait(false);
            return 1;
        }
    }

    /// <summary>Find a usable `udb` binary, downloading the matched release if needed.</summary>
    private static async Task<string> ResolveBinaryAsync()
    {
        // 1) PATH, if its version matches.
        var onPath = FindOnPath();
        if (onPath is not null && VersionMatches(onPath))
        {
            return onPath;
        }

        // 2) per-user cache.
        var cached = CachedBinaryPath();
        if (File.Exists(cached))
        {
            return cached;
        }

        // 3) download the matching release asset.
        return await DownloadAsync(cached).ConfigureAwait(false);
    }

    private static string ExeName => RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ? "udb.exe" : "udb";

    private static string? FindOnPath()
    {
        var path = Environment.GetEnvironmentVariable("PATH") ?? string.Empty;
        var sep = RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ? ';' : ':';
        foreach (var dir in path.Split(sep, StringSplitOptions.RemoveEmptyEntries))
        {
            var candidate = Path.Combine(dir.Trim(), ExeName);
            if (File.Exists(candidate))
            {
                return candidate;
            }
        }
        return null;
    }

    private static bool VersionMatches(string binary)
    {
        try
        {
            var psi = new ProcessStartInfo(binary, "--version")
            {
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
            };
            using var proc = Process.Start(psi);
            if (proc is null) return false;
            var stdout = proc.StandardOutput.ReadToEnd();
            proc.WaitForExit(5000);
            return stdout.Contains(Version, StringComparison.Ordinal);
        }
        catch
        {
            return false;
        }
    }

    private static string CacheDir()
    {
        // ~/.cache/udb/<version> on Unix, %LOCALAPPDATA%\udb\<version> on Windows.
        string baseDir;
        if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
        {
            baseDir = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
        }
        else
        {
            var xdg = Environment.GetEnvironmentVariable("XDG_CACHE_HOME");
            baseDir = !string.IsNullOrEmpty(xdg)
                ? xdg
                : Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), ".cache");
        }
        var dir = Path.Combine(baseDir, "udb", Version);
        Directory.CreateDirectory(dir);
        return dir;
    }

    private static string CachedBinaryPath() => Path.Combine(CacheDir(), ExeName);

    /// <summary>Map the current OS/arch to the published release asset name.</summary>
    private static string AssetName()
    {
        string os =
            RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ? "windows" :
            RuntimeInformation.IsOSPlatform(OSPlatform.OSX) ? "macos" :
            "linux";
        string arch = RuntimeInformation.OSArchitecture switch
        {
            Architecture.X64 => "x86_64",
            Architecture.Arm64 => "aarch64",
            var other => other.ToString().ToLowerInvariant(),
        };
        string ext = RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ? ".exe" : string.Empty;
        // e.g. udb-linux-x86_64, udb-windows-x86_64.exe, udb-macos-aarch64
        return $"udb-{os}-{arch}{ext}";
    }

    private static async Task<string> DownloadAsync(string destination)
    {
        var asset = AssetName();
        var url = $"https://github.com/{Repo}/releases/download/v{Version}/{asset}";
        await Console.Error.WriteLineAsync($"udb-launcher: downloading {url}").ConfigureAwait(false);

        using var http = new HttpClient();
        http.DefaultRequestHeaders.UserAgent.ParseAdd($"udb-csharp-launcher/{Version}");
        using var resp = await http.GetAsync(url, HttpCompletionOption.ResponseHeadersRead).ConfigureAwait(false);
        resp.EnsureSuccessStatusCode();

        var tmp = destination + ".partial";
        await using (var fs = File.Create(tmp))
        {
            await resp.Content.CopyToAsync(fs).ConfigureAwait(false);
        }

        if (!RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
        {
            // chmod 0755
            var psi = new ProcessStartInfo("chmod", $"755 \"{tmp}\"") { UseShellExecute = false };
            using var p = Process.Start(psi);
            p?.WaitForExit(5000);
        }

        File.Move(tmp, destination, overwrite: true);
        return destination;
    }

    /// <summary>Exec the resolved binary, forwarding args and the exit code.</summary>
    private static int Exec(string binary, string[] args)
    {
        var psi = new ProcessStartInfo(binary) { UseShellExecute = false };
        foreach (var a in args)
        {
            psi.ArgumentList.Add(a);
        }
        using var proc = Process.Start(psi)
            ?? throw new InvalidOperationException($"failed to start {binary}");
        proc.WaitForExit();
        return proc.ExitCode;
    }
}
